Feat side bar/#114
Alecell/octopost pull request #136
Opened 2023-08-24 17:52 UTC by flaviafreirec

Issue: #114 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- Create sidebar and header section.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
Adjust main container borders and paddings

- **Cause**
The borders and paddings was just for testing, and were conflicting with our new components

- **Solution**
Remove borders and adjust paddings
</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- [Add new `header` section](https://github.com/Alecell/octopost/commit/9d15434a9db65607b0f78b86286c111c95509f25)
- [Add new `sidebar` section](https://github.com/Alecell/octopost/pull/123/commits/581a64898de9d6a6f7f367f0237bcb6aa682cf7b)
- [Adjust sizes of `home` containers](https://github.com/Alecell/octopost/commit/142c850d9059d860b7ca927425fd3ba99369cf59)

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![page](https://github.com/Alecell/octopost/assets/54037222/bf8fdb5d-fce4-4c80-a239-87e15929647c)

![3](https://github.com/Alecell/octopost/assets/54037222/df6b6bc6-5dac-47b1-adef-fd446c2e0e8f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

2023-08-24 22:22 UTC, aalmeida00 requested changes

2023-08-24 22:22 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +}
Isso daqui nao deveria estar no base.scss e me pergunto além se isso nao deveria funcionar no normalize.css

2023-08-25 17:22 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +  background-color: #f5eff4;
```suggestion
  background-color: #000;

  background-color: #f5eff4;
```

Tem dois background-color.

2023-08-25 19:50 UTC, kingjotaro commented
A senhorita Flavia não assinou o PR

2023-08-25 22:58 UTC, aalmeida00 approved these changes

2023-08-28 16:40 UTC, flaviafreirec commented
adicionei o ladle stories para o header e sidebar hj c um novo commit

2023-08-28 21:14 UTC, aalmeida00 approved these changes

2023-08-28 21:40 UTC, merged