feat: Tabber Tabs for viewing selected networks
Alecell/octopost pull request #138
Opened 2023-08-25 19:47 UTC by kingjotaro

Tabs for viewing selected networks

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

![image](https://github.com/Alecell/octopost/assets/23247383/a9242650-b185-42bd-822c-9123f647c5a9)

2023-08-25 22:33 UTC, hxsggsz commented
tem alguma coisa que ta fazendo o build falhar no seu código, pode dar uma olhada nisso?

2023-08-25 22:46 UTC, hxsggsz requested changes

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/Tabber.module.scss
> +  padding: 1.5rem;
tenta usar valores multiplos por 2, ex 1.4 ou 1.6

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/Tabber.tsx
> +  ));
eu não sou muito fã de uma variável que tem um map de html dentro, talvez criar um componente separado ou juntar tudo nesse componente seja uma ideia melhor

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/Tabber.tsx
> +      </div>
```suggestion
        <TabsTabber
          socialItem={socialItem}
          selectedTab={selectedTab}
          onTabClick={handleTabClick}
        />
```

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +  justify-content: center; /* Adicionado para alinhamento horizontal */
acho que esse comentário é redundante

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +  }
mesma coisa dos valores multiplos por 2

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/components/Tabs/TabsTabber.tsx
> +function TabsTabber({ socialItem, selectedTab, onTabClick }: ITabsTabberProps) {
acho que ficaria melhor nao desestruturar a props aqui

2023-08-25 22:46 UTC, hxsggsz commented on src/styles/base.scss
> +  font-size: 90%;
mantém o `font-size` como `62.5%`, ele está assim para transformar 1rem === 10px

2023-08-25 22:46 UTC, hxsggsz commented on src/components/Tabber/Tabber.spec.tsx
> +  });
seu teste está bom, mas acredito que da pra testar mais, por exemplo se o tab está com o estilo de foco quando clica e se ele perde o estilo quando outro elemento é clicado

2023-08-25 23:10 UTC, aalmeida00 requested changes

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/Tabber.spec.tsx
> +  });
Isso, nao precisa exatamente testar o estilo, mas acredito que a sua tab mude a classe no dom dependendo do estado. Entao isso cabe aqui pra testar se essa classe está mudando.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +  justify-content: center; /* Adicionado para alinhamento horizontal */
True

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +  color: var(--m-3-sys-light-primary, #868687);
Acredito que nao vamos usar css variables, pode deixar só a cor chumbada mesmo.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +    color: var(--m-3-sys-light-primary, #7033e0);
Aqui a mesma coisa das css variables.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.module.scss
> +    border-bottom: 0.2rem solid currentColor;
Border nao precisa ser rem, pode colocar px.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.tsx
> +function TabsTabber({ socialItem, selectedTab, onTabClick }: ITabsTabberProps) {
Sim seguindo o nosso styleguide, a gente nao desestrutura props. Pode ajustar por favor.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/Tabs/TabsTabber.tsx
> +  );
Eu vi a flavia colocando svgs em um arquivo separado, o que voce acha de adotarmos isso?  Um arquivo junto com o componente.

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/TextAreaTabber/TextAreaTabber.module.scss
> +  display: none;
Qual é a do display none aqui?

2023-08-25 23:10 UTC, aalmeida00 commented on src/components/Tabber/components/TextAreaTabber/TextAreaTabber.tsx
> +function TextAreaTabber({ socialItem, selectedTab }: ITabsTabberProps) {
Nao desestruturar

2023-08-25 23:10 UTC, aalmeida00 commented on src/styles/base.scss
> +  font-size: 90%;
Exatamente, esse font-size aqui do base nao é alterado nunca. 

Aqui ele faz a conversao do REM ser multiplo de 10, se tu muda aqui, todo mundo que usou proporçao 10 pro rem, fica esquisito. Dito isso, talvez os seus estilos estejam errados e precisem ser alterados. Afinal aqui 1rem = 14.4px

2023-08-25 23:32 UTC, aalmeida00 commented on src/components/Tabber/Tabber.module.scss
> +  justify-content: start;
Aqui que está quebrando seu ci, eu acho.
```suggestion
  justify-content: flex-start;
```

2023-08-28 02:32 UTC, kingjotaro commented on src/components/Tabber/components/TextAreaTabber/TextAreaTabber.module.scss
> +  display: none;
esse compo vai ser apagado depois, mas a ideia é que todas as áreas de textos sejam renderizadas e mostrada somente a selecionada via css

2023-08-28 03:00 UTC, kingjotaro commented on src/components/Tabber/components/Tabs/TabsTabber.tsx
> +  );
esse svg eu tentei componetizar e pegou fogo, tbm não entendi o motivo não, olhei o da flavia e tinha feito algo similar mas ainda assim não carregava

2023-08-29 21:28 UTC, aalmeida00 approved these changes

2023-08-30 21:32 UTC, aalmeida00 approved these changes

2023-08-30 23:24 UTC, Alecell approved these changes

2023-08-30 23:26 UTC, merged