Feat accordion
Alecell/octopost pull request #139
Opened 2023-08-25 23:00 UTC by hxsggsz

Closes #119 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

create social accordion component
</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>
create SocialAccordion folder with all necessaries files, refactor toggleSocialMedia component to follow the figma design and create a new component inside toggleSocialMedia to handle the image logic.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![2023-08-25-19-53-33](https://github.com/Alecell/octopost/assets/103784814/95a84a1d-f6fd-4b2d-ae22-4e261e2686ee)

error variant:
![image](https://github.com/Alecell/octopost/assets/103784814/7188b1c8-518f-4561-b37c-95e7b14b324d)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

because of the path alias, i couldn't create the tests for the accordion  #127 
</details>

2023-08-25 23:31 UTC, aalmeida00 requested changes

2023-08-25 23:31 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.tsx
> +import test from '../../../assets/logo.png';
Esse nome aqui nao tá bom

2023-08-25 23:31 UTC, aalmeida00 commented on src/components/ToggleSocialMedia/components/UserImage/UserImage.tsx
> +  // in this way will show the first one
Pode remover esse comentário, o código por sí só já é explicativo.

2023-08-27 19:15 UTC, hxsggsz commented
ready to merge

2023-08-29 21:33 UTC, aalmeida00 requested changes
Ajustar as variaveis de acordo com a do tema que temos.
Senti falta de um teste pro SocialAccordion.

2023-08-29 21:33 UTC, aalmeida00 commented on src/assets/logo.png
Arquivo .png é bad smell, nao consegue exportar svg?

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.module.scss
> +    outline-color: #7033e0;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.module.scss
> +  border: 1px solid #cbc4cf;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.module.scss
> +    color: #49454e;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.module.scss
> +    color: #c00016;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/Switch/Switch.module.scss
> +  outline-color: #7033e0;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/ToggleSocialMedia/ToggleSocialMedia.module.scss
> +  border-bottom: 1px solid #cac4d0;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/ToggleSocialMedia/ToggleSocialMedia.module.scss
> +    outline-color: #7033e0;
theme color

2023-08-29 21:33 UTC, aalmeida00 commented on src/components/ToggleSocialMedia/components/UserImage/UserImage.module.scss
> +  background-color: #eaddff;
theme color

2023-08-30 23:19 UTC, aalmeida00 requested changes

2023-08-30 23:19 UTC, aalmeida00 commented on src/components/SocialAccordion/SocialAccordion.spec.tsx
> +    it('renders the intern content of accordion whe is open', () => {
```suggestion
    it('renders the intern content of accordion when is open', () => {
```

2023-08-30 23:20 UTC, Alecell requested changes

2023-08-30 23:20 UTC, Alecell commented on src/components/SocialAccordion/SocialAccordion.tsx
> +        {isOpen && (
Função

2023-08-30 23:20 UTC, Alecell commented on src/components/ToggleSocialMedia/components/UserImage/UserImage.tsx
> +  );
Arrumar

2023-08-30 23:20 UTC, Alecell commented on src/components/SocialAccordion/SocialAccordion.tsx
> +            {props.accountList.map((accounts) => (
Função

2023-08-30 23:20 UTC, Alecell commented on src/components/SocialAccordion/SocialAccordion.tsx
> +            )}
Função

2023-08-31 18:05 UTC, aalmeida00 approved these changes

2023-09-05 18:52 UTC, Alecell requested changes

2023-09-05 18:52 UTC, Alecell commented on src/components/SocialAccordion/SocialAccordion.tsx
> +  const openLabel = isOpen ? 'open' : 'closed';
Move isso pra área de declarações de variaveis, perto do useState

2023-09-05 18:52 UTC, Alecell commented on src/components/ToggleSocialMedia/components/UserImage/UserImage.tsx
> +  return props.image !== '' ? renderProfileImage() : renderImagePlaceholder();
```suggestion
  return props.image ? renderProfileImage() : renderImagePlaceholder();
```

2023-09-05 20:29 UTC, Alecell approved these changes

2023-09-05 20:29 UTC, merged