Feat/main text#131
Alecell/octopost pull request #144
Opened 2023-08-29 20:48 UTC by flaviafreirec

<details open> 
  <summary>
    <b>Feature #131 </b>
  </summary>

</details>

- **Description**
add style for the main content and text area and edited the variables from sidebar

</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- [edit `sidebar.modules.scss`](https://github.com/Alecell/octopost/commit/27510b113fe543f257573fcd60823f2f1998660c)

- [edit main content and textarea style](https://github.com/Alecell/octopost/commit/b991fee2cde9b9d539e5b73cc54ef83535e5c538)
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![main](https://github.com/Alecell/octopost/assets/54037222/6b8ea96e-611d-4355-bec2-111a1058ca58)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

2023-08-29 21:37 UTC, aalmeida00 requested changes

2023-08-29 21:37 UTC, aalmeida00 commented on src/components/CharacterLimit/CharacterLimit.module.scss
> +@import '../../styles/global';
Por enquanto o import vai ser assim até ajustar o tsconfig pra conseguir buildar direito com os path alias

2023-08-29 21:37 UTC, aalmeida00 commented on src/components/TextArea/TextArea.module.scss
> +    background-color: rgb(250, 250, 250);
Esse rgb nao tá no tema? Verificar se for um base white que a gente usa no projeto e colocar no tema.

2023-08-29 21:37 UTC, aalmeida00 commented on src/components/TextArea/TextArea.module.scss
> +    resize: vertical;
Será que o resize é necessário? 🤔 Pensando em como está o layout do fig

2023-08-29 21:37 UTC, aalmeida00 commented on src/components/ComposerEditor/ComposerEditor.module.scss
> +  right: 65.5rem;
Será que esse right com rem nao vai dá ruim? 🤔

2023-08-30 21:33 UTC, aalmeida00 approved these changes

2023-08-30 23:13 UTC, Alecell requested changes

2023-08-30 23:13 UTC, Alecell commented on src/components/TextArea/TextArea.module.scss
> +    box-sizing: border-box;
Coloca essa prop no main.scss para tudo

2023-08-31 18:06 UTC, aalmeida00 approved these changes

2023-09-05 18:47 UTC, Alecell approved these changes

2023-09-05 18:47 UTC, aalmeida00 approved these changes

2023-09-05 18:47 UTC, merged