Create composer base test and fix path alias on jest
Alecell/octopost pull request #148
Opened 2023-08-31 03:04 UTC by aalmeida00

Closes #127

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Create the compose editor base test, The main issue here is to fix the path alias from Jest

</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- Create composer editor test
- Fix jest issue to resolve path alias

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

## Jest fix path alias
| Before | After |
|--------|--------|
| ![image](https://github.com/Alecell/octopost/assets/61947632/cb810202-a256-4c76-9d05-05fe2522b2c9)| ![image](https://github.com/Alecell/octopost/assets/61947632/1a758cab-2a4b-4110-a965-f46441094b90) | 

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-08-31 14:12 UTC, Alecell requested changes

2023-08-31 14:12 UTC, Alecell commented on package.json
> +      "^~components(.*)$": "<rootDir>/src/components$1"
Já aproveita e faz isso pra todos os alias que temos no `tsconfig`

2023-09-03 23:41 UTC, Luiginicoletti approved these changes
Parece bom 😁

2023-09-05 18:45 UTC, Alecell approved these changes

2023-09-05 18:45 UTC, merged