feat: add new search clue component
Alecell/octopost pull request #152
Opened 2023-09-06 15:13 UTC by flaviafreirec

feat #122 

<details open> 
  <summary>
    <b>Search Clue</b>
  </summary>

<details open>
- **Description**
- add new `search clue` component

</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- create searchClue component
- add scss for search clue
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![Screenshot_2](https://github.com/Alecell/octopost/assets/54037222/33b5237c-b3ca-420a-8be4-e21c67ba80bc)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

He only have the component with label and value and the scss is created, but it is not yet integrated as we are working on the search component.
</details>

2023-09-06 15:20 UTC, aalmeida00 requested changes

2023-09-06 15:20 UTC, aalmeida00 commented on src/components/SearchClue/SearchClue.tsx
> +      <button className={scss.clearButton}>Clean</button>
Esse botao vai receber uma função pra dar clear no value, certo?

2023-09-06 15:20 UTC, aalmeida00 commented on src/components/SearchClue/SearchClue.tsx
> +// import { useState } from 'react';
```suggestion
```

2023-09-06 15:20 UTC, aalmeida00 commented on src/components/SearchClue/SearchClue.module.scss
> +  box-shadow: 0 1px 3px 0 #0000004d;
Não temos variável de cor pra essa variação no box shadow?

2023-09-08 02:07 UTC, aalmeida00 approved these changes

2023-09-11 12:59 UTC, flaviafreirec commented
![Screenshot_2](https://github.com/Alecell/octopost/assets/54037222/1bf862b5-08bf-4b87-8e38-d2a42b302879)

Ajustes do último commit

2023-09-12 02:06 UTC, Alecell commented
1) Porque não tem teste?
2) Porque o componente parece meio fino de mais, não?
3) atualizar a branch, tem conflito

2023-09-12 19:18 UTC, flaviafreirec commented
![Screenshot_3](https://github.com/Alecell/octopost/assets/54037222/9cfa26f0-11d2-4238-8560-155a8be253f8)


componente 12/09

também adicionei os testes

2023-09-12 19:18 UTC, flaviafreirec commented
> ![Screenshot_3](https://user-images.githubusercontent.com/54037222/267436993-9cfa26f0-11d2-4238-8560-155a8be253f8.png)
> 
> componente 12/09
> 
> também adicionei os testes

E esse clean ta com esse efeito pra ver o hover, mas é só quando passa o cursor

2023-09-12 20:31 UTC, kingjotaro commented on src/components/SearchClue/SearchClue.module.scss
> +@import '../../styles/global';
use @use instead import 
https://sass-lang.com/documentation/at-rules/use/

2023-09-12 21:03 UTC, flaviafreirec commented on src/components/SearchClue/SearchClue.module.scss
> +@import '../../styles/global';
o @use ta funcionando ja? o @aalmeida00  falou que era pra usar o import por enquanto ate resolver o @use

2023-09-12 21:13 UTC, kingjotaro commented on src/components/SearchClue/SearchClue.module.scss
> +@import '../../styles/global';
já funciona, testa assim 
`@use 'caminho/global' `
e para aplicar o estilo 
`font-family: global.$mainFont;`

2023-09-14 14:13 UTC, Alecell approved these changes

2023-09-14 14:13 UTC, merged