feat: add scrollbar for sidebar container
Alecell/octopost pull request #153
Opened 2023-09-06 18:43 UTC by flaviafreirec

Closes #32  

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- add `scrollbar` to the sidebar container 
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![scroll](https://github.com/Alecell/octopost/assets/54037222/f66afaf1-8a13-455f-8bf8-65f070220c34)
![semscroll](https://github.com/Alecell/octopost/assets/54037222/0cfb936e-2613-41a2-9045-d7a42d8fce10)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

2023-09-07 15:18 UTC, Alecell requested changes

2023-09-07 15:18 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.module.scss
> +    }
Descola um pouco o scroll da lateral

2023-09-08 02:07 UTC, aalmeida00 reviewed
Só ajustar o ponto do Ale.

2023-09-12 02:02 UTC, Alecell approved these changes

2023-09-12 02:02 UTC, merged