fix: fixing sass
Alecell/octopost pull request #154
Opened 2023-09-07 18:21 UTC by kingjotaro

#150 Fixing Sass @use

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

2023-09-08 02:05 UTC, aalmeida00 requested changes

2023-09-08 02:05 UTC, aalmeida00 commented on package.json
> -    "normalize.css": "^8.0.1",
Cara, eu acho que a gente precisa do normalize aqui, pq tu removeu?

Tenta importar ele como node_modules/normalize/normalize ao invés de ~normalize/normalize.css

2023-09-08 08:13 UTC, kingjotaro commented on package.json
> -    "normalize.css": "^8.0.1",
normalize não é algo para normalizar o css em diferentes navegadores? o app só vai rodar no electron que é chromium, acho que não necessita dele

2023-09-08 21:26 UTC, aalmeida00 commented on package.json
> -    "normalize.css": "^8.0.1",
Não, o normalize é uma biblioteca para fazer o 'reset' do css de campos padrões do html, é core pra nossa padronização de estilos.

http://necolas.github.io/normalize.css/

2023-09-12 02:21 UTC, Alecell requested changes
Não ia atualizar todos os arquivos de sass nesse PR?

2023-09-13 01:07 UTC, aalmeida00 requested changes
só tem esses lugares com @import?

2023-09-19 16:44 UTC, closed without merging