feat: Add flowIssues
Alecell/octopost pull request #156
Opened 2023-09-12 18:30 UTC by JpBurgarelli

Add issues flow

- **Description**
A description was made of how beginners can catch their  issues.

2023-09-13 01:06 UTC, aalmeida00 submitted a review, later dismissed

2023-09-14 14:11 UTC, Alecell requested changes

2023-09-16 22:31 UTC, aalmeida00 requested changes
voce criou um novo arquivo e nao deletou o antigo.

E a branch está desatualizado

2023-09-21 01:28 UTC, aalmeida00 submitted a review, later dismissed
LGTM 🔥

2023-09-21 17:17 UTC, Alecell submitted a review, later dismissed

2023-09-21 17:18 UTC, Alecell commented
Adicionar o link para o arquivo

2023-09-28 19:34 UTC, aalmeida00 approved these changes

2023-10-02 00:26 UTC, merged