Feat 134: Many media inputs
Alecell/octopost pull request #160
Opened 2023-09-19 16:54 UTC by flaviafreirec

Closes 

<details open> 
  <summary>
    <b>Feature #134 </b>
  </summary>
  
  Many Media Inputs
</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>
- create many media inputs
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
  
![2023-09-19-10-52-29](https://github.com/Alecell/octopost/assets/54037222/38358dbb-b69e-4995-b973-472d14f952f9)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

At the moment I'm still creating tests and fixing bugs in ladle's story
</details>

2023-09-19 22:48 UTC, hxsggsz requested changes

2023-09-19 22:48 UTC, hxsggsz commented on src/components/ManyInputMedias/ManyInputs.tsx
> +            const newId = new Date().getTime();
em vez disso você pode usar o própio datetime do arquivo que você ta adicionando no input
![image](https://github.com/Alecell/octopost/assets/103784814/bae82840-e081-4f67-898c-579295a0091f)

2023-09-19 22:48 UTC, hxsggsz commented on src/components/ManyInputMedias/ManyInputs.tsx
> +            setArrayImages([...arrayImages, { id: newId, file }]);
``
```
            setArrayImages((prevState) => [...prevState, { id: newId, file }]);
```

2023-09-19 22:48 UTC, hxsggsz commented on src/components/ManyInputMedias/ManyInputs.tsx
> +      {arrayImages.map((f: TManyMediaInputsImages) => (
```suggestion
// evita variáveis de uma letra só, tenta sempre ser a mais clara o possivel
// não precisa tipar o `map` porque o state ja tem a sua tipagem
      {arrayImages.map((files) => (
```

2023-09-19 22:48 UTC, hxsggsz commented on src/components/ManyInputMedias/ManyInputs.tsx
> +};
tenta usar interfaces pra seguir o styleguide e deixa em um arquivo separado

2023-09-19 22:48 UTC, hxsggsz commented on src/components/ManyInputMedias/ManyInputs.tsx
> +import React, { useState } from 'react';
```suggestion
// React já é importado automaticamente em todo arquivo `.tsx`
import { useState } from 'react';
```

2023-09-19 22:51 UTC, hxsggsz commented
seu componente tá muito bom, só tem dois detalhes, ta faltando testes unitários e o componente `InputMedia` ta desatualizado, provavelmente vai ter que esperar meu pr ser aprovado pra poder usar o componente completamente finalizado no seu pr

2023-10-03 03:41 UTC, Alecell requested changes

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.ct.spec.tsx
Adiciona um teste de render só de zoas

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.module.scss
mantem a hierarquia das tags nos estilos

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.stories.tsx
> +  // eslint-disable-next-line no-console
Adiciona uma rule no eslint pra que possemos usar console dentro de `.stories`

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.tsx
> +  }, [props.files]);
Me explica pq isso é necessário. Se esse é o input media, pq ele recebe media do pai? É pq da lista? Se for isso, tudo bem, mas porque precisa de um `useEffect`?

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.tsx
> +    );
Vou chamar a polícia!!!!!!11111111ONZE 🚨🚨🚨🚨🚨🚨

Temos aqui um ternário multiline dentro de um map? EU VO MORRE

Arruma

2023-10-03 03:41 UTC, Alecell commented on src/components/InputMedia/InputMedia.tsx
> +      {mediaSelected.length > 0 ? renderMedia() : renderEmptyImagePlaceholder()}{' '}
Porque `{' '}`?

2023-10-03 03:41 UTC, Alecell commented on src/components/ManyInputMedias/ManyInputs.tsx
> +        </div>
Cria um componente separado pra isso tudo, tem muita coisa aqui dentro de um map. Diminuir o conteúdo do map melhora a leitura

2023-10-03 03:41 UTC, Alecell commented on src/components/ManyInputMedias/ManyInputs.tsx
> +    // Para cada arquivo carregado, criamos um novo grupo com um único arquivo
Comentário em ingles

2023-10-09 20:02 UTC, closed without merging