feat: Add Main Composer Container
Alecell/octopost pull request #161
Opened 2023-09-22 20:57 UTC by JpBurgarelli

Feat #130

- **Description**
- Create new Main Composer text area

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/30197026/98c78085-d22a-4756-a67f-6e778e15cde9)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Tests weren`t created
</details>

2023-09-25 16:03 UTC, Alecell commented
O padding lateral ainda ta muito pequeno, precisa aumentar

2023-09-25 16:04 UTC, Alecell requested changes
Comentário anterior

2023-09-26 19:31 UTC, aalmeida00 requested changes

2023-10-03 03:24 UTC, Alecell commented
@JpBurgarelli atualiza a imagem, por enquanto eu diria que ainda precisa ajustar o padding

2023-10-03 03:26 UTC, Alecell requested changes

2023-10-03 03:26 UTC, Alecell commented on src/components/MainComposer/MainComposer.module.scss
Aqui tem alguns problemas:
1) Vc não ta mantendo a hierarquia das tags no CSS
2) Vc ta usando muita tag crua no CSS, isso é uma má pratica, sempre coloque classes, ou não referencie o container. Evitar ao máximo tags cruas no CSS

2023-10-03 14:42 UTC, Alecell requested changes
Agora parece que o tracinho n ta centralizado. Outra coisa é que vc n ta dando resolved nas conversations. Precisa

2023-10-05 02:34 UTC, Alecell approved these changes

2023-10-05 23:57 UTC, aalmeida00 approved these changes

2023-10-06 00:08 UTC, merged