Input media
Alecell/octopost pull request #167
Opened 2023-10-09 20:45 UTC by flaviafreirec

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- create the inputMedia component
- create manyInputMedias component
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![Screenshot_6](https://github.com/Alecell/octopost/assets/54037222/667f4049-8ecb-4c9a-a60b-be6782413906)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
Juntamos a branch inputMedia (do hx) com a do manyInputs (flávia) 
</details>

2023-10-11 20:57 UTC, flaviafreirec commented
![ig](https://github.com/Alecell/octopost/assets/54037222/e28a968c-8f13-4674-9f46-89c4a8ba610d) 

componente atualizado

2023-10-12 03:09 UTC, aalmeida00 requested changes
Algumas sugestoes simples.

O CI quebrou, parece que tem algo errado no teste xD.

2023-10-15 22:18 UTC, Alecell requested changes
Porque os testes created não tão marcado?

2023-10-15 22:18 UTC, Alecell commented on src/components/ManyInputMedias/ManyInputs.mock.tsx
> +// https://github.com/microsoft/playwright/issues/27439
Mesma coisa do outro comentário

2023-10-15 22:18 UTC, Alecell commented on src/components/ManyInputMedias/ManyInputs.tsx
Melhora o nome desse componente e o nome do componente deve ser o mesmo do arquivo

2023-10-15 23:02 UTC, hxsggsz commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
> +jest.spyOn(window, 'scrollTo');
o framer motion tava fazendo dar erro no console por causa do window.scrollTo então eu mockei isso pra parar com o erro, como não é algo que faria sentido testar pra mim eu não usei durante o teste

2023-10-15 23:04 UTC, hxsggsz commented on src/assets/imagetest.jpg
a gente precisava de mais uma imagem no projeto pra poder testar a feature de adicionar mais de uma imagem de uma vez no `ManyInputs`

2023-10-16 15:20 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/components/SocialAccordion/SocialAccordion.spec.tsx
> +jest.spyOn(window, 'scrollTo');
god

2023-10-23 17:30 UTC, aalmeida00 approved these changes

2023-10-24 13:51 UTC, merged