feat: Merge and fix the SearchClue and inputSearch on sidebar
Alecell/octopost pull request #171
Opened 2023-10-18 12:07 UTC by Luiginicoletti

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Merge two components "SearchClue" and "inputSearch" on Sidebar.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/17785028/2c48888e-cbfe-414e-b32b-0627d21af658)

![image](https://github.com/Alecell/octopost/assets/17785028/60fe451f-9c63-471b-a38b-0dd14428233c)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [x] Tests created
</details>

2023-10-18 12:10 UTC, aalmeida00 submitted a review, later dismissed

2023-10-18 17:41 UTC, aalmeida00 submitted a review, later dismissed

2023-10-18 20:20 UTC, flaviafreirec approved these changes

2023-10-18 22:32 UTC, aalmeida00 commented
![image](https://github.com/Alecell/octopost/assets/61947632/23303362-1ddf-43f6-82aa-021afe9555df)
@Luiginicoletti tem algo errado aqui. 

Olha nao tem nenhum texto no input e o X está habilitado, pode verificar?

2023-10-18 23:18 UTC, aalmeida00 approved these changes

2023-10-18 23:19 UTC, Luiginicoletti commented
Opa, corrigido @aalmeida00 obrigado.

2023-10-19 13:46 UTC, flaviafreirec submitted a review, later dismissed

2023-10-20 17:48 UTC, Alecell requested changes

2023-10-20 17:48 UTC, Alecell commented on src/components/InputSearch/IInputProps.types.ts
Tenha ctz do q vc disse na call

2023-10-20 17:48 UTC, Alecell commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +        ) : null}
Ajustar o multiline ternário

2023-10-20 17:52 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +        ) : null}
sai daqui maluco

2023-10-23 13:21 UTC, aalmeida00 requested changes

2023-10-23 13:21 UTC, aalmeida00 commented on src/components/InputSearch/InputSearch.tsx
> +    // if (props.handleClear) props.handleClear();
Remover comentário

2023-10-23 13:21 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +        ) : null}
Esse ternário ainda está multiline

2023-10-23 13:25 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.tsx
> +    // if (props.handleClear) props.handleClear();
Eu tinha deixado porque nao sabia se iriamos precisar mais pra frente, mas apaguei, obg

2023-10-23 16:40 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +        ) : null}
Consertei, obg.

2023-10-24 15:31 UTC, Luiginicoletti commented on src/components/InputSearch/IInputProps.types.ts
Revisei.

2023-10-24 15:50 UTC, Alecell submitted a review, later dismissed

2023-10-24 16:25 UTC, kingjotaro submitted a review, later dismissed

2023-10-26 19:05 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.tsx
> +    // if (props.handleClear) props.handleClear();
Resolvido

2023-10-27 14:08 UTC, kingjotaro approved these changes

2023-10-27 14:26 UTC, flaviafreirec submitted a review, later dismissed

2023-10-27 14:47 UTC, GabrielTrindadeC submitted a review, later dismissed
LGTM

2023-10-27 14:48 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +        ) : null}
.

2023-10-27 14:48 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.tsx
> +    // if (props.handleClear) props.handleClear();
.

2023-10-27 17:02 UTC, aalmeida00 submitted a review, later dismissed

2023-10-29 09:38 UTC, Alecell requested changes
Só uma pergunta

2023-10-29 09:38 UTC, Alecell commented on .vscode/extensions.json
Faz sentido esse arquivo vir no pr?

2023-10-29 12:43 UTC, Luiginicoletti commented on .vscode/extensions.json
Nossa eu realmente não sei oque é isso e como foi parar ai, quer que eu retire?

2023-10-29 22:32 UTC, aalmeida00 requested changes
Rolou bastante modificacao nos arquivos, eu tinha aprovado anteriormente, mas agora tenho essas sugestoes aqui para serem feitas.

2023-10-29 22:32 UTC, aalmeida00 commented on src/components/InputSearch/InputSearch.tsx
> +  const divIcons = () => (
Esse nome tã meio ruim né

2023-10-29 22:32 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +          error={false}
Nunca vai ter estado de erro nesse campo?

2023-10-29 22:32 UTC, aalmeida00 commented on src/components/InputSearch/InputSearch.spec.tsx
> +    expect(inputElement.value).toBe('Value');
Esse teste aqui voce tá mudando ele errado. Ele nao está limpando o campo, tá errado. Tem que ajustar isso.

2023-10-30 13:16 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.tsx
> +  const divIcons = () => (
Usei o chat gpt e achei esse aqui melhor, o que acha?

2023-10-30 13:18 UTC, Luiginicoletti commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +          error={false}
Eu achei que quando tivesse um erro seria tratado aqui pelo sidebar e enviado para inputSearch, no lugar do false. Achei que essa fosse a forma correta, consegue me ajudar a resolver isso?

2023-10-30 13:39 UTC, aalmeida00 commented on src/pages/home/components/Sidebar/Sidebar.tsx
> +          error={false}
Concordo com voce, vendo melhor agora pode ficar assim false, e no futuro vai ser tratado pela sidebar, está correto.

2023-10-30 20:30 UTC, Luiginicoletti commented on src/components/InputSearch/InputSearch.spec.tsx
> +    expect(inputElement.value).toBe('Value');
Feito, obrigado pela ajuda.

2023-10-30 21:47 UTC, aalmeida00 approved these changes

2023-10-31 17:39 UTC, Alecell approved these changes

2023-10-31 17:39 UTC, merged