Componente de preview
Alecell/octopost pull request #182
Opened 2023-11-01 14:01 UTC by PiluVitu

Closes [Componente de preview#178](https://github.com/Alecell/octopost/issues/178)

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- Foi criado um componente container para o preview
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

-  Criado Pasta `Componente Preview`
-  Criado `PreviewContainer.stories.tsx`
     - Usado para adicionar o componente no StoryBook
-  Criado `PreviewContainer.module.scss`
     - Usado para estilizar o componente 
-  Criado `PreviewContainer.types.ts`
     - Usado para adicionar a tipagem do componente
-  Criado `PreviewContainer.tsx`
     - Componente do container 
 -  Criado `PreviewContainer.spec.tsx`
     - Teste Unitário para saber se o componente container está renderizando corretamente o conteudo
 -   `PreviewContainer` inserido na `Home`
     - O componente foi inserido na home com o `Preview` sendo passado na propriedade e renderizando como esperado 
  -  `ComposeEditor` removido da `Home`
     - No layout do figma não deveria ter na da acima do main content, então removi o componente que estava lá
  -  `PreviewContainer` property `preview` alterado para `children` para respeitar o padrão do projeto
 -   `PreviewContainer.spec.tsx` agora indentifica o texto inserido no componente.
 -  Move `PreviewContainer` to `Tabber`
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

- Light
![image](https://github.com/Alecell/octopost/assets/69992923/5e76d1f3-dd6a-4a76-9e42-3d58a98ace22)

- Dark 
![image](https://github.com/Alecell/octopost/assets/69992923/defbb4f1-5a7f-4d43-b4f9-410635d423e0)

- Adicionado no `Tabber` com o `Preview` posicionado de maneira correta
![image](https://github.com/Alecell/octopost/assets/69992923/a6ba464d-bb8b-45ac-94e3-9552ff2dd6dc)
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

- Menção mais do que honrosa ao @aalmeida00 que me ajudou com os teste e ao @Luiginicoletti que me ensinou a usar o ladle.

- Gostaria de Ressaltar que o componente preview está sem o tamanho correto devido ao problema do ladle

2023-11-01 14:02 UTC, aalmeida00 requested changes
Falta testes unitários :pray:

2023-11-01 14:02 UTC, aalmeida00 commented on src/components/ComponentPreview/PreviewContainer.tsx
> +      {/* Remover H1 quando inserir o componente view */}
```suggestion
```

2023-11-02 15:05 UTC, Alecell commented
Coloca o componente na posição dele baseado no layout man!

2023-11-06 12:20 UTC, Luiginicoletti commented
Muito bom !!!

2023-11-06 19:55 UTC, hxsggsz requested changes

2023-11-06 19:55 UTC, hxsggsz commented on src/components/ComponentPreview/PreviewContainer.spec.tsx
> +const title = <h1 data-testid="custom-element"> teste </h1>;
evita usar `testid`, usa somente em ultimos casos, nesse seu exemplo você pode pegar pelo texto do html.

2023-11-06 19:55 UTC, hxsggsz commented on src/components/ComponentPreview/PreviewContainer.tsx
> +  return <section className={scss.container}>{props.preview}</section>;
usa a convenção de sempre nomear como `children`  uma props do tipo `ReactNode` para sempre saber que essa prop vai ser sempre um filho do componente pai

2023-11-06 19:57 UTC, PiluVitu commented on src/components/ComponentPreview/PreviewContainer.tsx
> +  return <section className={scss.container}>{props.preview}</section>;
Vlw pae, vou mudar agora

2023-11-06 20:09 UTC, PiluVitu commented on src/components/ComponentPreview/PreviewContainer.spec.tsx
> +const title = <h1 data-testid="custom-element"> teste </h1>;
A linha de validação do teste ta ok ? Foi a maior dúvida q eu tinha

2023-11-06 20:52 UTC, hxsggsz commented on src/components/ComponentPreview/PreviewContainer.spec.tsx
> +const title = <h1 data-testid="custom-element"> teste </h1>;
sim, sim é um componente simples esse, não tem muito o que testar além disso

2023-11-06 20:56 UTC, hxsggsz submitted a review, later dismissed

2023-11-06 20:56 UTC, hxsggsz commented on src/components/ComponentPreview/PreviewContainer.stories.tsx
> +    </div>
```suggestion
    <div>
      <PreviewContainer>
        <Preview>Preview Imaginário</Preview>
      </PreviewContainer>
    </div>
```

2023-11-06 20:56 UTC, hxsggsz commented on src/components/ComponentPreview/PreviewContainer.spec.tsx
> +      render(<PreviewContainer children={title} />);
```suggestion
      render(<PreviewContainer>
        <h1> teste </h1>
      </PreviewContainer>);
```

2023-11-07 11:35 UTC, PiluVitu commented on src/components/ComponentPreview/PreviewContainer.spec.tsx
> +      render(<PreviewContainer children={title} />);
Noss brigadão pae, fazer aki

2023-11-07 17:10 UTC, Alecell requested changes
Ta no lugar errado

2023-11-09 11:35 UTC, Alecell approved these changes
ltmj

2023-11-09 13:58 UTC, aalmeida00 approved these changes

2023-11-09 14:01 UTC, merged