feat: add checkbox component
Alecell/octopost pull request #192
Opened 2023-11-10 14:14 UTC by alvarogfn

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-11-17 00:00 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.module.scss
> +      margin: -1px;
valor negativo e em px, tenta tirar isso pq é bad smell

2023-11-17 00:02 UTC, hxsggsz commented on src/components/Accordion/Accordion.tsx
> +  ...props
detalhe importante, não desestruturamos props e separamos o componente do export, olha no [styleguide](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md) e segue todos os padrões que ta la.

2023-11-17 00:03 UTC, hxsggsz commented on src/components/Accordion/Accordion.spec.tsx
> +    const content = screen.queryByText('content');
só usa o `query` quando for testar que algo não está em tela, tirando isso usa `get` ou `find` quando for necessário.

2023-11-17 00:05 UTC, hxsggsz commented on src/components/Accordion/index.ts
> +export * from './Accordion.types';
```suggestion

```
não seguimos esse padrão, apaga todos arquivos index.ts

2023-11-17 00:07 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.module.scss
> +}
muda as unidades de medida pra REM em toda propiedade que não seja border ou derivado de border, da uma lida nesse [artigo que o ale traduziu sobre unidades de medidas css](https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/).

2023-11-17 00:09 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.spec.tsx
> +});
segue o nosso [styleguide](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md) pra criar os testes

2023-11-17 00:17 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.tsx
> +      {...labelProps}
eu não sou muito fã de usar spread operator pras props, acho que fica confuso pra saber quais props você ta passando.

2023-11-17 00:18 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.tsx
> +const Checkbox = forwardRef<HTMLInputElement, TCheckboxProps>(function Checkbox(
qual a função do `forwardref` aqui?

2023-11-17 00:19 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.tsx
> +  { children, labelProps, className, onChange, style, ...props },
sem desestruturação de props

2023-11-17 00:20 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.types.ts
> +  onChange?: TCheckboxChangeHandler;
acho que tem coisas que são desnecessariamentes opicionais ai

2023-11-17 00:23 UTC, hxsggsz commented on src/components/FirstComment/FirstComment.tsx
> +export function FirstComment({ ...props }: TFirstCommentProps) {
sem desestruturação

2023-11-17 00:24 UTC, hxsggsz commented on src/components/Accordion/Accordion.types.ts
> +  renderContent: () => ReactNode;
isso pode ser um children com o tipo reactNode direto

2023-11-17 00:29 UTC, hxsggsz commented on src/components/Accordion/Accordion.tsx
> +  const headerElement = renderHeader();
usa a função direto

2023-11-17 00:32 UTC, hxsggsz commented on src/components/Accordion/Accordion.types.ts
> +export type TAccordionProps = ComponentPropsWithoutRef<'div'> & {
acho que esse `ComponentPropsWithoutRef` ta sendo passado muitas vezes desnecessariamente só pra pegar o classname, sugiro evitar isso ao maximo pq só alguns componentes precisam mesmo se utilizar disso e você ta usando isso em todos.

2023-11-17 00:33 UTC, hxsggsz commented on src/components/FirstComment/FirstComment.module.scss
> +}
mesma coisa das unidades de medida

2023-11-17 00:35 UTC, hxsggsz requested changes

2023-11-17 00:35 UTC, hxsggsz commented on src/components/Checkbox/Checkbox.stories.tsx
> +};
mantém o padrão dos outros stories

2023-11-17 11:58 UTC, alvarogfn commented on src/components/Accordion/Accordion.types.ts
> +export type TAccordionProps = ComponentPropsWithoutRef<'div'> & {
É para expor a API básica do elemento HTML do componente. Isso dá acesso a tipagens das roles, arias e eventos para quem ta utilizando de fora.

2023-11-17 12:09 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.tsx
> +const Checkbox = forwardRef<HTMLInputElement, TCheckboxProps>(function Checkbox(
Tornar o componente usável em bibliotecas de formulário.

2023-11-17 12:32 UTC, alvarogfn commented on src/components/Accordion/Accordion.tsx
> +}
Coloquei esse Accordion nele.

2023-11-17 12:38 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.tsx
> +      {...labelProps}
Qual alternativa?

2023-11-17 12:39 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.module.scss
> +@use '../../styles/global' as *;
Dizer para o sass que eu não preciso de prefixo

2023-11-17 23:32 UTC, aalmeida00 submitted a review, later dismissed
Parabéns, teu código está ótimo, realmente.  Só tem alguns pontos para alinhar mais ainda com nosso styleguide de código. Mas no geral está aprovada, nada crítico.

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/Accordion/Accordion.spec.tsx
> +});
A gente evita com que o its estejam muito grandes, pode ajustar? Ai acabamos colocando um describe.

```suggestion
describe('Accordion', () => {
  describe('when isOpen is false', () => {
    it('body cannot render', () => {
      makeSut({ isOpen: false });

      const content = screen.queryByText('content');

      expect(content).not.toBeInTheDocument();
    });
  });

describe('when isOpen is true', () => {
  it('body can render', () => {
    makeSut({ isOpen: true });

    const content = screen.getByText('content');

    expect(content).toBeVisible();
  });


});
});
```

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/Accordion/Accordion.stories.tsx
> +      isOpen={true}
```suggestion
      isOpen
```

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/Checkbox/Checkbox.module.scss
> +  padding: 0.438rem !important;
qual que é a gamb desse padding aqui com esse important? :thinking:

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/Checkbox/Checkbox.spec.tsx
> +  it('call [onChange] when checkbox be clicked', async () => {
Aqui vale o mesmo ponto do outro teste.

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/Checkbox/Checkbox.spec.tsx
> +};
Quer explicar pra galera esse código lá no TIL do discord? Po isso daqui é mt brabo tá.

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/FirstComment/FirstComment.module.scss
> +  border: 1px solid #e6e1e6;
Essa corzinha nao tá no DS?

2023-11-17 23:32 UTC, aalmeida00 commented on src/components/FirstComment/FirstComment.spec.tsx
> +  it('should open Accordion when checkbox is marked', async () => {
Mesma coisa do outro teste.

2023-11-19 13:16 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.spec.tsx
> +};
Beleza.

2023-11-19 13:41 UTC, alvarogfn commented on src/components/Checkbox/Checkbox.module.scss
> +  padding: 0.438rem !important;
O reset de CSS está com especificidade maior que os outros estilos.

![image](https://github.com/Alecell/octopost/assets/62889807/22e5a424-5805-4630-9065-608aeb39066b)

mas essa propriedade não é mais necessária pq eu coloquei width e height.

2023-11-19 13:42 UTC, alvarogfn commented on src/components/FirstComment/FirstComment.module.scss
> +  border: 1px solid #e6e1e6;
nop, 
![image](https://github.com/Alecell/octopost/assets/62889807/150116f6-403e-4b54-ac07-e06bbaf5687b)

2023-11-20 15:26 UTC, aalmeida00 approved these changes

2023-11-21 18:04 UTC, hxsggsz approved these changes
![image](https://github.com/Alecell/octopost/assets/103784814/ea87e30e-72c2-4ec3-8a27-b4aa2460011f)

LGTM

2023-11-21 21:07 UTC, aalmeida00 approved these changes

2023-11-21 21:07 UTC, merged