177 error boundaries
Alecell/octopost pull request #201
Opened 2023-11-14 03:09 UTC by Sherlockzen

Closes [Error Boundaries #177 ](https://github.com/Alecell/octopost/issues/177)

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Create ErrorBoundary component
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

- Create folder ErrorBoundary in components folder with it's tests, stories, types and the component itself.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

- The tips in the mirio about git is just perfect! Thanks for who wrote this.
</details>

2023-11-14 04:59 UTC, hxsggsz commented
teu pr tem que apontar pra branch master não?

2023-11-14 05:08 UTC, hxsggsz requested changes

2023-11-14 05:08 UTC, hxsggsz commented on src/components/ErrorBoundary/ErrorBoundary.types.ts
> +  error: null;
aqui você ta dizendo que o error vai ser null mesmo quando o `hasError` ser `true`, isso ta certo?

2023-11-14 05:08 UTC, hxsggsz commented on src/components/ErrorBoundary/ErrorBoundary.spec.tsx
> +// import { TBoundaryProps } from './ErrorBoundary.types';
```suggestion

```

2023-11-14 05:08 UTC, hxsggsz commented on src/components/ErrorBoundary/ErrorBoundary.spec.tsx
> +      });
é possivel usar a api `render` do testing library react pra realizar esses testes? digo isso pra manter o padrão de testes no projeto igual ta no styleguide.

2023-11-14 05:08 UTC, hxsggsz commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  // }
```suggestion
 
```

2023-11-16 00:39 UTC, Sherlockzen commented on src/components/ErrorBoundary/ErrorBoundary.types.ts
> +  error: null;
Acabei de alterar aqui, agora o error pode ser Error ou null.

2023-11-16 00:40 UTC, Sherlockzen commented on src/components/ErrorBoundary/ErrorBoundary.spec.tsx
> +// import { TBoundaryProps } from './ErrorBoundary.types';
Removido, tanks.

2023-11-16 00:41 UTC, Sherlockzen commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  // }
Removido.

2023-11-17 00:35 UTC, hxsggsz approved these changes

2023-11-17 23:35 UTC, aalmeida00 approved these changes
god. Só esse pequeno ajustezinho

2023-11-17 23:35 UTC, aalmeida00 commented on src/components/ErrorBoundary/ErrorBoundary.spec.tsx
> +  };
Esse cara aqui pode ficar dentro do contexto que é utilizado. Se nao ele fica meio jogado.

2023-11-19 14:32 UTC, Sherlockzen commented on src/components/ErrorBoundary/ErrorBoundary.spec.tsx
> +  };
Feito! Coloquei ele dentro do 'render "fallback" element'.

2023-11-20 15:27 UTC, aalmeida00 approved these changes

2023-11-20 21:34 UTC, GabrielTrindadeC approved these changes

2023-11-20 21:41 UTC, merged