feat(text area input): Created the textarea input component
Alecell/octopost pull request #22
Opened 2023-08-08 01:46 UTC by flaviafreirec

![placeholder](https://github.com/Alecell/octopost/assets/54037222/702c0792-be48-46be-a0f1-abbe3397c178)

2023-08-08 02:06 UTC, aalmeida00 commented on src/components/Textarea.tsx
> +      cols={50}
O tamanho não poderia ser dinamico pra esse componente ter uma flexibilidade maior?

2023-08-08 02:07 UTC, aalmeida00 commented on src/index.tsx
> +    <CustomTextArea value="placeholder" />
@Alecell talvez já esteja nos planos, mas vale pensar na utilização do Storybook, ou algum similar, pra ajudar no desenvolvimento desses componentes.

2023-08-08 02:09 UTC, aalmeida00 approved these changes
LGTM.

No PR vale adicionar um pouco mais de informação, talvez um gif do funcionamento do componente, como ele está funcionando com a responsividade, etc.

2023-08-08 13:43 UTC, Alecell commented
> LGTM

LGTM, pra mim, é mais LGTJ. Ao inves de "Looks Good To Me" fica mais dahora "LeGal Tamo Junto" 🤣

VALEUZÃO PELA FORÇA ontem man!

2023-08-08 13:44 UTC, Alecell commented on src/index.tsx
> +    <CustomTextArea value="placeholder" />
Não se precisaria pq não vamos ter tantos componentes assim (eu acho), mas é uma sugestão POG!!

2023-08-08 13:45 UTC, Alecell commented on src/components/Textarea.tsx
> +      cols={50}
Aqui a boa mesmo é usar um scss mesmo @flaviafreirec!

2023-08-08 15:22 UTC, aalmeida00 commented on src/pages/components/textArea/Textarea.scss
> +}
Faltou uma linha no final aqui.

2023-08-08 15:26 UTC, aalmeida00 commented on src/index.tsx
> +    <CustomTextArea value="placeholder" />
@Alecell se quiser abrir uma issue e jogar nos meus peitos, eu posso tentar subir o setup desse cara pra geral.

2023-08-09 02:58 UTC, Alecell requested changes

2023-08-09 02:58 UTC, Alecell commented on src/index.tsx
> +    <CustomTextArea value="Digite algo..." />
Noooo, isso aqui n pode ser importado aqui, tem q ser no `App`

2023-08-09 02:58 UTC, Alecell commented on src/index.tsx
> +import CustomTextArea from './pages/components/textArea/Textarea';
Não existe esse import

2023-08-09 02:58 UTC, Alecell commented on src/index.tsx
>      <App sim="nao" />
Sua branch n parece estar atualizada com a ultima versão da develop

2023-08-09 02:58 UTC, Alecell commented on tsconfig.json
> +      "~components/*": ["src/pages/components/*"],
NÃO, tava certo esse role antes!

Ajusta, vamos falar na daily sobre a estrutura de arquivos

2023-08-09 19:13 UTC, closed without merging