Nico 35268942
Alecell/octopost pull request #24
Opened 2023-08-08 14:55 UTC by Luiginicoletti

Fixed file names and folder architecture

2023-08-08 15:11 UTC, aalmeida00 requested changes

2023-08-09 00:16 UTC, Luiginicoletti commented
Quando eu tento editar para develop gera um erro: 
"A pull request already exists for base branch 'develop' and head branch 'nico-35268942"

Talvez esteja duplicado acho que eu posso deletar?

2023-08-09 02:41 UTC, aalmeida00 commented
Verifica se esse PR é igual a esse aqui, https://github.com/Alecell/octopost/pull/25. Se for pode fechar esse.

2023-08-09 02:54 UTC, Alecell commented
É ta estranho

2023-08-09 21:32 UTC, closed without merging