Feat/copia do texto
Alecell/octopost pull request #25
Opened 2023-08-08 19:52 UTC by Luiginicoletti

In this pr the CopyText feature was made.

A textbox component that will have a conditional edit.

It receives a state and replicates it in the textbox, also giving, if you prefer, the option to continue editing through the textbox itself, keeping the previous state value

CopyText.tsx
`const TextCopy: React.FC<ITextCopyProps> = (props) => {
  const [text, setText] = useState('');
  const [isEdited, setIsEdited] = useState(false);

  const updateText = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setText(e.target.value);
    setIsEdited(true);
  };

  return (
    <textarea value={isEdited ? text : props.text} onChange={updateText} />
  );
};`

using component 

`
 const [inputText, setInputText] = useState('');

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputText(event.target.value);
  };
  
<input
              type="text"
              value={inputText}
              onChange={handleInputChange}
              placeholder="Texto a ser replicado"
            />
            <TextCopy text={inputText} />`
            
            
![image](https://github.com/Alecell/octopost/assets/17785028/cb31b8d6-c045-4fd0-9a6a-885195484d7d)

![image](https://github.com/Alecell/octopost/assets/17785028/a8ca46bf-e829-4308-aef3-aff92872d9f4)

2023-08-08 20:40 UTC, aalmeida00 requested changes

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/components/CharacterCountDown/CharacterCountDown.module.scss
Se não tem nenhum estilo a ser escrito, pode deletar o arquivo.

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
> +    </div>
Não precisa da div aqui, use um React Fragment ao invés da div.

O fragment não gera item no DOM, fazendo com que fique melhor a perfomance desse componente.
https://react.dev/reference/react/Fragment

```suggestion
    <>
      <textarea
        value={text}
        onChange={handleChange}
        maxLength={maxLength}
        placeholder={`Digite até ${maxLength} caracteres`}
      />
      <p>{maxLength - text.length} caracteres restantes</p>
    <>
```

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/components/TextCopy/TextCopy.module.scss
> +}
EOF.

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  white-space: pre-wrap; /* Para manter quebras de linha */
Código já é auto explicaivo, pode evitar o uso de comentários.

```suggestion
  user-select: text;
  white-space: pre-wrap; 
```

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/home/home.module.scss
> +.Sections{
Faltou um espaço aqui.

```suggestion
}

.Sections {
```

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/home/home.module.scss
> +}
EOF

2023-08-08 20:40 UTC, aalmeida00 commented on src/pages/components/TextCopy/TextCopy.tsx
> +    setText(e.target.value);
Dá pra deixar o event explicito aqui.

```suggestion
  const updateText = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setText(event.target.value);
```

2023-08-09 00:12 UTC, Luiginicoletti commented
Todos os requisitos foram corrigidos!

2023-08-09 02:08 UTC, aalmeida00 approved these changes
lgtm 🔥

2023-08-09 02:13 UTC, Luiginicoletti commented
éoque?

2023-08-09 02:45 UTC, Alecell requested changes

2023-08-09 02:45 UTC, Alecell commented on src/App.module.scss
> +.App {
classe sempre em letra minuscula, `camelCase`, não `PascalCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
> +      <p>{maxLength - text.length} caracteres restantes</p>
isso não é `p`, é `span`

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
Renomear o arquivo pra algo mais sobre "limite" e não sobre "countdown"

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
> +    if (newText.length <= maxLength) {
Ainda não falamos sobre styleguide, mas esse `if` é sem bracket.

Esse limite também não é algo obstrutivo que impede de digitar mais, ele é apenas um visual clue. O `if` na verdade pode ser removido

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
> +  maxLength,
Ainda sobre styleguide, evite desestruturação pra n dar aquele pau de nomeclatura que tivemos no `text`

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/CharacterCountDown/CharacterCountDown.tsx
> +        maxLength={maxLength}
Não usar essa propriedade aqui

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  margin-top:20px;
Não usar `px` para `margin`, usar `rem`

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  padding: 8px;
Não usar `px` para `padding`, usar `rem`

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  font-size: 14px;
`font-size` **sempre** em `rem` (ou `em`, mas nesse caso é `rem`, vamos abordar isso na daily)

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  white-space: pre-wrap;
Why?

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
Parece que esse arquivo n ta sendo usado em lugar nenhum, apagar

2023-08-09 02:45 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.tsx
> +interface ITextCopyProps {
Seguindo o styleguide que ainda não falamos, colocar isso num arquivo separado `TextCopy.types.ts`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +body, h1, h2, h3, h4, h5, h6, p, blockquote, pre, dl, dd, ol, ul, figure, hr {
Hm... Isso aqui n deveria ter sido removido ontem?

To confuso, me lembra de falar disos na daily.

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +.Sections {
Classes devem usar `camelCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +.SectionContainer {
Classes devem usar `camelCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +.Logo {
Classes devem usar `camelCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +.NavBar {
Classes devem usar `camelCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +.Home {
Classes devem usar `camelCase`

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +*, ::before, ::after {
NOO

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +  height: 50px;
`height` fixa é um crime, não faça isso. Aco que vamos ter que fazer um aulão sobre relatividade de layout.

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +  margin-left: 10px;
Esse é um dos poucos casos que ta tudo bem usar altura e largura fixa, mas ó, to de olho!

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +  margin-left: 10px;
Mas `margin` com `px` é crime memo

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +  gap: 10px;
`gap` com `px` é algo interessante, podemos falar sobre. Me lembra

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.module.scss
> +  height: full;
![image](https://github.com/Alecell/octopost/assets/13935760/8294adcc-2b56-4e4c-96f4-2da9a4f1f13e)

2023-08-09 02:45 UTC, Alecell commented on src/pages/home/home.tsx
> +        <div className="">
Evitar propriedade vazia. Se não tem oq colocar, não coloque a propriedade.

2023-08-09 21:35 UTC, aalmeida00 commented
This PR resolve:

https://github.com/Alecell/octopost/issues/18 -> add react router dom
https://github.com/Alecell/octopost/issues/20 -> component character limit

2023-08-09 21:41 UTC, aalmeida00 requested changes
Vamos trocar os PX por REM.

Pode considerar a base do REM como 1rem = 10px.

2023-08-09 21:41 UTC, aalmeida00 commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  padding: 8px;
```suggestion
  padding: 0.8rem;
```

2023-08-09 22:20 UTC, aalmeida00 requested changes
Mudanças de styleguide
componentes:

`function() Componente {}
`
Definimos os componentes como function para que fique diferente do que é uma função do componente, do que é um coponente.

Funçoes
`const func () => {}
`

2023-08-09 22:20 UTC, aalmeida00 commented on src/pages/components/CharacterLimit/CharacterLimit.tsx
> +const CharacterCountdown: React.FC<ICharacterLimitProps> = (props) => {
Vamos seguir o styleguide e todo componente deve ser function.

```suggestion
function CharacterCountdown(props): React.FC<ICharacterLimitProps>{
```

2023-08-09 22:20 UTC, aalmeida00 commented on src/pages/components/TextCopy/TextCopy.tsx
> +const TextCopy: React.FC<ITextCopyProps> = (props) => {
Aqui a mesma coisa.

```suggestion
function TextCopy(props): React.FC<ITextCopyProps> {
```

2023-08-10 15:38 UTC, Alecell requested changes

2023-08-10 15:38 UTC, Alecell commented on src/pages/home/home.module.scss
> +}
Tudo isso aqui tem q ser removido desse arquivo, essas são regras que possivelmente vão fazer parte do Normalize.css e se ele não trouxer essas melhorias ai sim vamos colocar isso, mas no `base.css`, não no app!

2023-08-10 21:31 UTC, aalmeida00 requested changes

2023-08-10 21:31 UTC, aalmeida00 commented on src/App.tsx
> +    <div className={scss.App}>
```suggestion
    <div className={scss.app}>
```

2023-08-10 21:31 UTC, aalmeida00 commented on src/App.tsx
>  import scss from './App.module.scss';
```suggestion
import scss from './app.module.scss';
```

2023-08-10 21:31 UTC, aalmeida00 commented on src/pages/home/home.module.scss
> +  padding: 4px;
```suggestion
  padding: 0.4rem;
```

2023-08-11 03:04 UTC, aalmeida00 approved these changes

2023-08-11 12:25 UTC, Alecell requested changes

2023-08-11 12:25 UTC, Alecell commented on src/pages/components/CharacterLimit/CharacterLimit.tsx
> +      />
Esse `textarea` não existe aqui, só o `CharacterLimit` mesmo

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.tsx
> +import TextCopy from './../components/TextCopy/TextCopy';
usar path alias

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.tsx
> +          </div>
Vamo complicar isso aqui um porquinho, o character limit é um componente que vai ser usado **dentro** do `TextCopy`, esse `input` não existe, bem como a div do `CharacterLimit` que temos nesse file.

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.tsx
> +  const [inputText, setInputText] = useState('');
Isso qui pode ir embora pq o input n existe

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.tsx
> +import CharacterLimit from '../components/CharacterLimit/CharacterLimit';
Usar path alias

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.module.scss
> +  gap: 10px;
`gap` em `rem` tambem

2023-08-11 12:25 UTC, Alecell commented on src/pages/home/home.module.scss
Vc ta usando muito `width: 100vw` e `height: 100vh`, não é algo categoricamente errado, mas é um smell. Vamos falar sobre isso na daily! Me lembra!

2023-08-11 12:25 UTC, Alecell commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  white-space: pre-wrap;
Sinto no coração do meu fundo que tem algo errado aqui com stylelint, vamos falar na daily tbm. Me lembra!

2023-08-11 14:19 UTC, Luiginicoletti commented on src/pages/home/home.tsx
> +          </div>
Sim, é mais um componente visual para eu ver ele funcionando, assim que mergear vou unir na pagina inicial dentro do container correspondente.

2023-08-11 14:21 UTC, Luiginicoletti commented on src/pages/home/home.module.scss
É só pra ter um componente visual até ajustarmos os layouts.

2023-08-11 14:34 UTC, Luiginicoletti commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  white-space: pre-wrap;
Esses css são só para eu poder testar o componente, acho que deveriamos focar nesses css só quando tivermos o layout/figma resolvido não?

2023-08-11 14:34 UTC, Luiginicoletti commented on src/pages/components/TextCopy/TextCopy.module.scss
> +  white-space: pre-wrap;
Por enquanto estamos focando das funcionalidades

2023-08-11 14:35 UTC, Luiginicoletti commented
Vi que houve muito code review para css de componentes, esses css de componentes por hora estão sendo apenas para facilitar o desenvolvimento do componente, já que estamos focando nas funcionalidades até termos os padrões/estilos definidos pelo figma etc... não?

2023-08-11 14:38 UTC, Luiginicoletti commented
Alias, gostaria de fechar esse pr para poder focar no layout da pagina inicial e depois dos componentes já na pagina inicial, para ver como tudo vai ficar mesmo. esse é só o componente de copia-do-texto, acho que não faz sentido eu ficar mexendo no layout da pagina inicial daqui.

2023-08-11 16:17 UTC, merged