Tabber
Alecell/octopost pull request #39
Opened 2023-08-09 08:03 UTC by kingjotaro

Issue: 
Tabber #14 
Criado minha primeira task, testando qualidade dos commits e PR's

foto abaixo,

![image](https://github.com/Alecell/octopost/assets/23247383/8c74b350-2235-4690-bf99-c458af0c08fc)

2023-08-09 14:25 UTC, aalmeida00 requested changes
Sua branch está desatualizada com develop, vale checar.

E o seu PR está fora do nosso guide. Exemplos: https://github.com/Alecell/octopost/pull/37 https://github.com/Alecell/octopost/pull/27

2023-08-09 14:25 UTC, aalmeida00 commented on src/components/Tabber/tabber.module.scss
> +  .button {
```suggestion
  }
  
  .button {
```

2023-08-09 14:25 UTC, aalmeida00 commented on src/pages/home/index.tsx
> +      <Tabber></Tabber>
Esse componente não tem children, pode ser chamado assim.
```suggestion
      <Tabber />
```

2023-08-09 22:46 UTC, GabrielTrindadeC requested changes
Sua branch  parece desatualizada.

Evitar medidas absolutas (px) e usar medidas relativas.
Evitar index.tsx, utilizar nome do componente para nomenclatura dos arquivos em PascalCase

2023-08-09 22:46 UTC, GabrielTrindadeC commented on src/components/CharacterCountDown/index.tsx
> +interface ICharacterCountdownProps {
Separar as interfaces dos componentes em um arquivo separado por exemplo CharacterCountDown.types.ts

2023-08-09 22:46 UTC, GabrielTrindadeC commented on src/components/Tabber/tabber.module.scss
> +    max-width: 800px;
como ja vamos utilizar medidas relativas o max-width não faz sentido aqui.

2023-08-09 22:46 UTC, GabrielTrindadeC commented on src/components/Tabber/tabber.module.scss
> +    border-radius: 9999px;
```suggestion
    border-radius: 50%;
```

2023-08-10 00:43 UTC, Alecell requested changes

2023-08-10 00:43 UTC, Alecell commented on src/components/CharacterCountDown/index.tsx
Esse arquivo acho que ta desatualizado. Falar com o @Luiginicoletti pra atualizar e acertar certiho.

2023-08-10 00:43 UTC, Alecell commented on src/components/Tabber/index.tsx
> +const Tabber: React.FC = () => {
Usar `function` ao invés de arrow function

2023-08-10 00:43 UTC, Alecell commented on src/components/Tabber/tabber.module.scss
> +    max-width: 800px;
Só um adendo, realmente aqui n faz sentido, mas existem casos que precisamos do role!

2023-08-10 16:04 UTC, closed without merging