Input image
Alecell/octopost pull request #40
Opened 2023-08-09 09:55 UTC by kingjotaro

Issue: #31 
<details open> 
  <summary>
    <b>Button</b>
  </summary>  

  - [x] Issue linked
  - [x ] Build working correctly
  - [ ] Tests created
</details>

2023-08-09 14:24 UTC, aalmeida00 requested changes
Esse seu PR tá bem estranho, vale olhar o que pode ter acontecido. Tem alguns códigos no Nicoletti aqui.

Fora que ele está apontando para master, e não para develop aqui no git.

2023-08-09 14:44 UTC, kingjotaro commented on src/components/InputImage/input.module.scss
> +}
foi feito agora de madrugada, eu sei que fiz alguma caquinha pq não consegui dar commit usando CLI, ai fiz pelo atalho do vscódigo, fiz ele com base na branch do nico, não era dependente mas o develop antigo tava quebrando aqui

2023-08-10 00:37 UTC, Alecell requested changes

2023-08-10 00:37 UTC, Alecell commented on src/pages/home/index.module.scss
Esse arquivo é antigo, apagar. Tem algum coco no role como o @aalmeida00 mencionou!

2023-08-10 00:37 UTC, Alecell commented on src/pages/home/index.tsx
Esse arquivo ta numa versão desatualizada

2023-08-10 00:37 UTC, Alecell commented on src/components/InputImage/input.module.scss
> +    padding: 10px 20px;
Padding só com `rem`

2023-08-10 00:37 UTC, Alecell commented on src/components/InputImage/input.module.scss
> +    color: white;
Color com nome não existe no nosso projeto, talvez o stylelint n esteja rodando?

2023-08-10 00:37 UTC, Alecell commented on src/components/InputImage/index.tsx
> +
Evitar espaços desnecessários

2023-08-10 00:37 UTC, Alecell commented on src/components/InputImage/index.tsx
> +const InputImage: React.FC = () => {
Usar `function` conforme falamos na daily

2023-08-10 00:37 UTC, Alecell commented on src/components/CharacterCountDown/index.tsx
Esse arquivo ou não existe ou ele ta desatualizado. Fala com o @Luiginicoletti sobre isso pra vc atualizar pra versão mais recente.

2023-08-10 16:05 UTC, closed without merging