Feat/organizar containers pagina inicial
Alecell/octopost pull request #41
Opened 2023-08-09 15:22 UTC by Luiginicoletti

Issue: 

<details open> 
  <summary>
    <b>Home Page initial grid layout</b>
  </summary>

In this pr an initial homepage layout was created based on the given layout
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
![image](https://github.com/Alecell/octopost/assets/17785028/80d82dfd-2880-4ef6-bac8-2935d18e792c)

I put a responsivity on switches grid about minWidth and maxWidth
![image](https://github.com/Alecell/octopost/assets/17785028/cfd14e96-0007-4da3-8fca-f6539f83c9dc)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-08-09 22:24 UTC, aalmeida00 requested changes

2023-08-09 22:24 UTC, aalmeida00 commented on src/App.module.scss
> +  padding: 4px;
Transforma px em rem.

2023-08-09 22:24 UTC, aalmeida00 commented on src/App.module.scss
> +}
eof

2023-08-10 00:30 UTC, Alecell requested changes

2023-08-10 00:30 UTC, Alecell commented on src/App.module.scss
> +body, h1, h2, h3, h4, h5, h6, p, blockquote, pre, dl, dd, ol, ul, figure, hr {
Pq isso ainda existe? 
![image](https://github.com/Alecell/octopost/assets/13935760/4e3f404e-ff3c-46d5-a7e6-402eec56e592)

Vamos usar o [normalize css](https://necolas.github.io/normalize.css/) pra resetar os roles

2023-08-10 00:30 UTC, Alecell commented on src/App.module.scss
> +
ajustar a identação

2023-08-10 18:17 UTC, aalmeida00 approved these changes
lgtm

2023-08-10 18:54 UTC, Alecell requested changes

2023-08-10 18:54 UTC, Alecell commented on src/App.module.scss
> +}
Remover

2023-08-10 18:57 UTC, Luiginicoletti commented on src/App.module.scss
> +}
Feito!

2023-08-10 18:59 UTC, aalmeida00 approved these changes

2023-08-10 19:03 UTC, Alecell requested changes

2023-08-10 19:03 UTC, Alecell commented on src/App.module.scss
>  }
Apaga

2023-08-10 19:04 UTC, Alecell requested changes

2023-08-10 19:04 UTC, Alecell commented on src/App.tsx
> +        <div className={scss.gridTabs}></div>
Ajusta isso tbm, coloca um self closed por enquanto

2023-08-10 19:08 UTC, Alecell approved these changes

2023-08-10 19:09 UTC, merged