feat: create textarea input
Alecell/octopost pull request #42
Opened 2023-08-09 19:13 UTC by flaviafreirec

feat #16

Issue: #16 

<details open> 
  <summary>
    <b>Text area Input</b>
  </summary>

This PR adds a new text entry area component using a <textarea> tag

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
 
![Screenshot_3](https://github.com/Alecell/octopost/assets/54037222/c8846e23-8ff2-4d91-b778-0972a32c3478)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-08-09 22:15 UTC, aalmeida00 requested changes

2023-08-09 22:15 UTC, aalmeida00 commented on src/pages/components/textArea/Textarea.tsx
> +}
Podemos colocar as interfaces dentro de um arquivo de types?

Crie um arquivo `TextArea.types.ts` e export essa interface e importe aqui.

2023-08-09 22:15 UTC, aalmeida00 commented on src/pages/components/textArea/Textarea.tsx
> +function CustomTextArea({ value }: ITextAreaProps) {
Vamos usar a nomenclatura de React.FC igual o nico fez nesse PR. https://github.com/Alecell/octopost/blob/954a564ac8671a1aa518cf334081838ea066129e/src/pages/components/CharacterLimit/CharacterLimit.tsx

E também evitar desestruturar as props

```suggestion
function CustomTextArea(props): React.FC {
```

2023-08-09 22:19 UTC, hxsggsz commented on src/pages/components/textArea/Textarea.module.scss
> +  padding: 10px;
nesse artigo do @Alecell sobre unidades de medidas, ele fala sobre sempre usar unidades relativas como `rem` em padding, e nunca medidas fixas como px. O arquivo `base.scss` onde é configurando o `font-size` do body como `62,5%` para poder trabalhar com rem ainda não foi mergeado mas não precisa se preocupar com isso porque o pr já ta pronto, só to aguardando uma revisão

2023-08-09 22:20 UTC, hxsggsz commented on src/pages/components/textArea/Textarea.module.scss
> +  padding: 10px;
artigo citado: https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/

2023-08-10 00:16 UTC, Alecell commented
Sobre seu PR:
Se uma categoria não tem nada, no seu caso o **bugfix**, pode remover toda a sessão.

@aalmeida00 no caso não precisamos de `feat` e `issue` ali no header né? No caso as duas coisas são a mesma né? Acho que da pra remover o `feat`.

2023-08-10 00:23 UTC, Alecell submitted a review, later dismissed
@aalmeida00 pontuou umas fitas dahoras que eu ia pontuar. BRABO

2023-08-10 00:23 UTC, Alecell commented on src/App.tsx
>  interface ITest {
Tipagens gerais do componente sempre colocar no arquivo `NomeDoComponent.types.ts`

2023-08-10 00:23 UTC, Alecell commented on src/pages/components/textArea/Textarea.tsx
> +interface ITextAreaProps {
Mesma fita das outras interfaces, já é algo pra adicionarmos no nosso styleguide

2023-08-10 01:50 UTC, aalmeida00 commented
> Sobre seu PR:

@Alecell 
>@aalmeida00 no caso não precisamos de feat e issue ali no header né? No caso as duas coisas são a mesma né? Acho que da pra remover o feat.

Isso mesmo, pode remover o feat. 🙏

2023-08-10 17:34 UTC, aalmeida00 requested changes

2023-08-10 17:34 UTC, aalmeida00 commented on src/pages/components/textArea/TextArea.types.ts
> +export default ITextAreaProps;
eof

2023-08-10 18:28 UTC, aalmeida00 approved these changes

2023-08-11 03:07 UTC, aalmeida00 approved these changes

2023-08-11 12:28 UTC, Alecell commented
@flaviafreirec vc ainda ta trampando no teste dessa feature né? Só pra confirmar!

2023-08-11 13:12 UTC, flaviafreirec commented
> @flaviafreirec vc ainda ta trampando no teste dessa feature né? Só pra confirmar!
> 
> Se ainda tiver faz igual o @aalmeida00 e coloca o PR como draft!

Siim! Coloquei como draft ✅

2023-08-11 20:58 UTC, aalmeida00 approved these changes

2023-08-11 21:43 UTC, aalmeida00 approved these changes

2023-08-11 21:43 UTC, merged