feat(Input Imagem Button): new feature button input image
Alecell/octopost pull request #51
Opened 2023-08-10 20:01 UTC by kingjotaro

Issue:  #31

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

created a new feature of a input image button
</details>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

![image](https://github.com/Alecell/octopost/assets/23247383/10165608-f08c-47ba-bceb-c1b563ed63f2)

2023-08-10 21:34 UTC, hxsggsz requested changes

2023-08-10 21:34 UTC, hxsggsz commented on src/components/InputImage/InputImage.module.scss
> +    color: white;
tenta não colocar cores pelo nome, segue sempre o padrão hexadecimal que nesse caso seria ` #fff `

2023-08-10 21:34 UTC, hxsggsz commented on src/components/InputImage/InputImage.tsx
> +      <button className={scss.image} onClick={() => inputRef.current?.click()}>
acho que da pra melhorar isso aqui, tenta trocar essa div que engloba tudo por uma label, coloca os estilos do botão na label e remove o o botão, assim também não vai ser necessário o useRef e vai fazer a mesma coisa.

2023-08-11 12:31 UTC, Alecell requested changes

2023-08-11 12:31 UTC, Alecell commented on src/components/InputImage/InputImage.tsx
> +  const inputRef = useRef<HTMLInputElement | null>(null);
200% que não precisamos de `useRef` aqui! Talvez uma abordagem legal seja o componente receber um array de label + children

2023-08-12 19:22 UTC, aalmeida00 requested changes
Falta testes

2023-08-12 19:22 UTC, aalmeida00 commented on src/components/InputImage/InputImage.tsx
> +        <input type="file" onChange={handleFileChange} />{' '}
Vale tirar esse espaço, geralmente o lint faz isso as vezes, ai pode tirar.



```suggestion
        <input type="file" onChange={handleFileChange} />
```

2023-08-13 16:22 UTC, Alecell requested changes

2023-08-13 16:22 UTC, Alecell commented on src/components/InputImage/InputImage.module.scss
> +    border-radius: 1rem;
Não necessariamente precisa usar `rem` em `border-radius`. Na verdade nesse caso talvez seja legal usar `px` pq provavelmente não vamos querer alterar o radius decorrent do tamanho da fonte.

2023-08-13 16:22 UTC, Alecell commented on src/components/InputImage/InputImage.module.scss
> +    display: inline;
Esse `display` não existe nesse caso. Para de fugir do `css`, precisa aprender ele.

2023-08-13 16:22 UTC, Alecell commented on src/components/InputImage/InputImage.tsx
> +  function handleFileChange(event: any) {
Funções internas devem ser com arrow function.

2023-08-13 16:22 UTC, Alecell commented on src/components/InputImage/InputImage.tsx
> +      {imageSelected && (
Não usar condicionais multiline

2023-08-17 22:39 UTC, aalmeida00 requested changes

2023-08-17 22:39 UTC, aalmeida00 commented on README.md
Sua branch está com um commit a mais

2023-08-17 22:39 UTC, aalmeida00 commented on src/components/InputImage/InputImage.module.scss
> +    height: 24px;
px

2023-08-17 22:39 UTC, aalmeida00 commented on src/components/InputImage/InputImage.spec.tsx
> +});
Vamos usar uma arquitetura de describe/it, isso tá fora do styleguide.
Cada teste precisa ter um describe, e cada assertion precisa ser um it

2023-08-17 22:39 UTC, aalmeida00 commented on src/components/InputImage/InputImage.tsx
> +  const icon = (
Vamos precisar trocar o nome disso,

2023-08-17 22:39 UTC, aalmeida00 commented on src/pages/home/home.tsx
> +              <InputImage></InputImage>
Self close

2023-08-18 21:02 UTC, aalmeida00 commented on src/components/InputImage/InputImage.module.scss
> +justify-content: center;
Esse stylelint tá meio estranho nao? Olha como tá aqui. Ele até passou no CI, mas nao ficou estranho essa identação?

2023-08-18 21:02 UTC, aalmeida00 commented on src/components/InputImage/InputImage.tsx
> +      <div> {imageElement}</div>
```suggestion
      <div>{imageElement}</div>
```

2023-08-18 21:02 UTC, aalmeida00 commented on src/components/InputImage/InputImage.tsx
> +    <img src={URL.createObjectURL(imageSelected)} alt="Imagem" />
Esse alt aqui tá meio generico né.

2023-08-18 21:22 UTC, kingjotaro commented on src/components/InputImage/InputImage.module.scss
> +justify-content: center;
se passou é pq funciona kkkkkkkkk, irei olhar no código

2023-08-18 21:23 UTC, kingjotaro commented on src/components/InputImage/InputImage.tsx
> +      <div> {imageElement}</div>
ai o stylelint faio

2023-08-18 21:24 UTC, kingjotaro commented on src/components/InputImage/InputImage.tsx
> +    <img src={URL.createObjectURL(imageSelected)} alt="Imagem" />
done

2023-08-18 21:51 UTC, aalmeida00 approved these changes
SGTM só ajustar o lint do inputImage.,module.scss

2023-08-18 21:51 UTC, aalmeida00 commented on src/components/InputImage/InputImage.module.scss
> +}
```suggestion
.imageInputed {
  display: flex;
  direction: row;

  align-items: center;
  justify-content: center;
}
```

2023-08-18 21:51 UTC, aalmeida00 commented on src/components/InputImage/InputImage.module.scss
> +}
irmao ainda tá errado teu lint uhdsahudshuasd

2023-08-19 16:04 UTC, Alecell requested changes

2023-08-19 16:04 UTC, Alecell commented on src/components/InputImage/InputImage.module.scss
> +}
É isso n podia passar

2023-08-19 16:04 UTC, Alecell commented on src/components/InputImage/InputImage.spec.tsx
> +      userEvent.click(icon);
Isso tem qu ser envolto por um `act`

2023-08-19 16:04 UTC, Alecell commented on src/components/InputImage/InputImage.tsx
> +  const fileInputRef = useRef<HTMLInputElement>(null);
Não existe `ref` aqui. Esse `useRef` pode ser removido

2023-08-19 16:04 UTC, Alecell commented on src/components/InputImage/InputImage.tsx
> +  const handleImageIconClick = () => {
Vc deve pegar a imagem a partir do evento que viria:

```suggestion
  const handleImageIconClick = (event) => {
```

2023-08-24 01:13 UTC, closed without merging