feat(new feature): Tabber #14
Alecell/octopost pull request #52
Opened 2023-08-10 20:25 UTC by kingjotaro

Issue: #14 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Tabber with social networks

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

2023-08-10 20:42 UTC, aalmeida00 requested changes

2023-08-10 20:42 UTC, aalmeida00 commented on src/components/Tabber/Tabber.module.scss
Arquivo em branco

2023-08-10 20:42 UTC, aalmeida00 commented on src/components/Tabber/Tabber.tsx
Acho que esse tabber tem que ser um pouco mais complexo. 

E não renderizar cada botão assim.

O ideal é ele receber um array de redes sociais e renderizar baseado nesse array.

2023-08-11 12:33 UTC, Alecell requested changes

2023-08-11 12:33 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
Sim esse componente é bem mais complexo que isso, ele recebe um array de redes sociais, baseado nelas, ele renderiza os tabs com seus respectivos conteúdos quando clicados respectivamente.

2023-08-11 15:09 UTC, kingjotaro commented on src/components/Tabber/Tabber.tsx
gotcha

2023-08-11 15:10 UTC, kingjotaro commented on src/components/Tabber/Tabber.module.scss
que estranho

2023-08-11 18:18 UTC, aalmeida00 requested changes

2023-08-11 18:18 UTC, aalmeida00 commented on src/components/Tabber/Tabber.module.scss
> +
Teu stylelint tá com problemas

2023-08-11 18:18 UTC, aalmeida00 commented on src/components/Tabber/Tabber.tsx
> +        </div>
Acho que nao ficou tao claro, mas é um começo.

O networks vai vir das props, e aí nela vamos renderizar a rede.

2023-08-11 18:18 UTC, aalmeida00 commented on src/components/Tabber/TabberNetworks.tsx
> +export const network = [
Nao é necessário

2023-08-12 19:21 UTC, aalmeida00 requested changes
Vale adicionar testes unitário também.

2023-08-13 16:18 UTC, Alecell requested changes

2023-08-13 16:18 UTC, Alecell commented on src/components/Tabber/Tabber.module.scss
> +
Sim, precisa ajustar, tem muito erro de identação

2023-08-13 16:18 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +      {network.map((networkItem) => (
Colocar `maps` derivados de funções, cria uma função que renderiza uma lista tipo `renderTabs` e nesse função vc usa o `map`, no corpo do componente usar apenas a chamada da função em si `{renderTabs()}`

2023-08-15 03:00 UTC, Alecell requested changes

2023-08-15 03:00 UTC, Alecell commented on src/components/Tabber/Tabber.module.scss
> +}
Sinto que isso subiu antes do `stylelint`, da uma verificada

2023-08-17 12:56 UTC, Alecell requested changes

2023-08-17 12:56 UTC, Alecell commented on src/App.tsx
> +      <Tabber socialList={networkList} children={''} />
O children não é um item isolado, ele é hardmente dependente do item da lista atual. Pra testar isso no mínimo vc precisa fazer um componente fake de textarea (ou usar oque ja existe) e ele deve permitir que vc atualize o campo de texto mesmotr trocando tabs, mantendo inclusive os estados anteriores dos outros componentes.

2023-08-17 12:56 UTC, Alecell commented on STYLEGUIDE.md
> +## Table of Contentsj
Marcado como resolved mas ainda ta com o `j` no fim.

2023-08-17 12:56 UTC, Alecell commented on src/App.tsx
> +import networkList from '~components/Tabber/data';
Má pratica, importar algo como default usando um nome diferente do arquivo. Pra tudo que não for componente vamos usar named exports

2023-08-17 12:56 UTC, Alecell commented on src/components/Tabber/Tabber.module.scss
> +}
Stylelint

2023-08-17 12:56 UTC, Alecell commented on src/components/Tabber/data.tsx
> +const networkListMock: ISocialItem[] = [
export básico, default apenas em  componentes

2023-08-17 13:17 UTC, kingjotaro commented on STYLEGUIDE.md
> +## Table of Contentsj
agora foi

2023-08-17 13:18 UTC, kingjotaro commented on src/components/Tabber/Tabber.module.scss
> +}
deveria ter ido no ultimo commit

2023-08-19 16:01 UTC, Alecell requested changes

2023-08-19 16:01 UTC, Alecell commented on src/components/Tabber/Tabber.module.scss
> +}
Stylelint

2023-08-19 16:01 UTC, Alecell commented on src/components/Tabber/Tabber.tsx
> +    </div>
Precisamos falar sobre, isso aqui n vai funcionar conforme o esperado

2023-08-19 16:01 UTC, Alecell commented on src/components/Tabber/data.tsx
> +  },
Nesses obejtos que o `children` vai ser definido.

2023-08-24 01:13 UTC, closed without merging