docs(CONTRIBUTING.md): Diretrizes de contribuição
Alecell/octopost pull request #56
Opened 2023-08-10 22:54 UTC by GabrielTrindadeC

Issue: #53 

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
CONTRIBUTING.md
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

2023-08-10 23:01 UTC, aalmeida00 approved these changes
🔥 lgtm @Alecell da uma olhada aqui

2023-08-11 12:37 UTC, Alecell requested changes
Brabissimo!!

2023-08-11 12:37 UTC, Alecell commented on CONTRIBUTING.md
> +3. **Crie uma Branch:** Crie uma branch para trabalhar nas suas alterações:
Seria legal avisar que é pra criar a branch a partir da develop

2023-08-11 12:37 UTC, Alecell commented on CONTRIBUTING.md
> +5. Código: Siga o Style guide [octopost/STYLEGUIDE.md at master · Alecell/octopost (github.com)](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
Isso aqui deveria ser bold tbm, não?

2023-08-11 12:37 UTC, Alecell commented on CONTRIBUTING.md
> +3. **Criação de Pull Request (PR):** Abra um Pull Request descrevendo suas alterações e fornecendo contexto sobre o que foi feito.
Talvez seja legal deixar claro que o PR é cross repo

2023-08-11 12:37 UTC, Alecell commented on CONTRIBUTING.md
> +- **Estilo de Código:** Siga as convenções de estilo de código existentes no projeto.
Coloca o link do MD

2023-08-11 14:17 UTC, aalmeida00 requested changes
Arruma esse comentário ai que tá assim:
![image](https://github.com/Alecell/octopost/assets/61947632/9101bce9-dc77-48f9-8e06-c5ab1f99df99)

2023-08-11 17:34 UTC, aalmeida00 approved these changes

2023-08-13 02:52 UTC, Alecell approved these changes

2023-08-13 02:54 UTC, merged