Feat: Add zunstand to project
Alecell/octopost pull request #58
Opened 2023-08-11 02:42 UTC by aalmeida00

Issue: #30 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

The provided task is to initialize a Zunstand setup on project. The main goal here is to add a state manager to simplify our life in the future, using a simple solution like Zunstand.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

- Added Zunstand library
- Create an example basic usage of a store
- Mocked Zunstand to work properly with jest
- Tested all the functionality of the store

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

[Zunstand had a peculiarity to configure jest](https://docs.pmnd.rs/zustand/guides/testing#jest), and to make the lib work properly with jest, I created a mock. 

</details>

2023-08-11 14:56 UTC, aalmeida00 commented on src/stores/usePostsStore.test.tsx
Só a força do hábito, vou arrumar.

2023-08-13 16:15 UTC, Alecell requested changes

2023-08-13 16:15 UTC, Alecell commented on package.json
> +    "typescript": "^5.1.6",
Typescript é `devDependencies`

2023-08-13 16:15 UTC, Alecell commented on src/components/Testinho/Testinho.spec.tsx
> +    it('render with de default value', () => {
`renders`

2023-08-13 16:15 UTC, Alecell commented on src/stores/__mocks__/zunstandMock.ts
Isso aqui deveria ta num arquivo de `helpers` ou `utils`, não? Oque acha? Se bem que eu concordo que por ele ser um mock do zustand faz todo o sentido ele ta aqui. Não sei 🤔

Isso aqui é um mock específico do teste que vc criou? Ou é um gerador de mock?

2023-08-13 16:15 UTC, Alecell commented on src/stores/usePostsStore.spec.tsx
Vamos discutir sobre isso, acho que não precisamos ter um teste do zustand em si, a questão é ele estar funcionando conforme esperamos no componente.

2023-08-13 21:32 UTC, aalmeida00 commented on package.json
> +    "typescript": "^5.1.6",
Estranho, já estava então em algum momento. Vou adicionar pra dev.

2023-08-13 21:36 UTC, aalmeida00 commented on src/stores/usePostsStore.spec.tsx
Eu também acho. Depois que criei o teste de 'increment' no componente, achei que talvez a lógica do hook pode ser atrelado para o componente.

Talvez não seja realmente necessário aqui mesmo. 
(em outros lugares eu vejo a galera testando o hook/store de forma isolada também).

2023-08-13 21:38 UTC, aalmeida00 commented on src/stores/__mocks__/zunstandMock.ts
1. Pensando que esse cara é um helper pra testar os hooks do Zunstand, cabe ele ficar em uma pasta isolada pra ser chamada.
2. Mas ele é realmente isso, um MOCK pra testar os hooks do zunstand, cabe ele ficar nesse escopo aqui.
3. Esse cara é um mock generico pra conseguir mockar o zunstand.

2023-08-15 02:54 UTC, Alecell commented on src/stores/usePostsStore.spec.tsx
Vamos manter pra referencia, mas assim que um componente usar nois capa fora!

2023-08-15 02:55 UTC, Alecell commented
Ae @aalmeida00 só precisa atualizar a branch, qual será, update with merge commit ou update with rebase???

TO COM MEDO DESSE CARAIO asidufgsddbtasfjysak

2023-08-15 22:54 UTC, aalmeida00 commented
>Ae @aalmeida00 só precisa atualizar a branch, qual será, update with merge commit ou update with rebase??? TO COM MEDO DESSE CARAIO asidufgsddbtasfjysak

@Alecell 
SQUASH AND MERGE COM FORÇA SEM DÓ NEM PIEDADE

2023-08-16 00:11 UTC, Alecell approved these changes

2023-08-16 00:11 UTC, Alecell commented
Só atualizar o bagulho man!! (medo de duplicação github da medo) masuygduadytgtys

2023-08-16 00:27 UTC, merged