Hxsggsz 35268942
Alecell/octopost pull request #6
Opened 2023-08-07 22:24 UTC by hxsggsz

On this pull request i make a toggle social media with a switch component using the checkbox input as a base for it

## The toggle social media component

To use this component you need to pass as props the social media name, here is the code example: 
```  
import { ToggleSocialMedia } from './components/toggleSocialMedia';

function App() {
  return (
	<ToggleSocialMedia socialMedia="Facebook" />
  );

}
  
export default App;
```

## The final result:

![2023-08-07-19-04-12](https://github.com/Alecell/octopost/assets/103784814/2936fdaa-a642-44e7-a096-0c31a982cfcc)

## How to use the switch component on your code:

You will need to pass two props to the component: the checked state as a boolean and the setChecked

here is an example in code how to use it

```
function App() {
  const [checked, setChecked] = useState(false);

  return (
      <Switch checked={checked} setChecked={setChecked} />
  );

}

  

export default App;
```

## Final result of the switch component

![2023-08-07-18-51-24](https://github.com/Alecell/octopost/assets/103784814/ed341b2d-7e36-4fd2-a0c2-3d180a57dc05)

2023-08-08 00:18 UTC, Alecell commented on src/styles/Swith.module.scss
> +    left: 20px;
isso pode melhorar, talvez ao inves de `20px` vc pode usar algo como `right: 0` talvez? Algo que garante que o componente continue funcionando independente do tamanho setado do switch

2023-08-08 00:19 UTC, Alecell commented on src/styles/ToggleSocialMedia.module.scss
> +  font-size: 24px;
`font-size` só com `rem`, da uma olhada nisso: https://twitter.com/alecell_/status/1641861282977529857

2023-08-08 00:20 UTC, Alecell commented on src/styles/ToggleSocialMedia.module.scss
> +}
Adiciona uma linha no fim do arquivo

2023-08-08 00:33 UTC, Alecell commented on src/styles/Swith.module.scss
> +    padding: 14px;
Padding só com `rem` tambem, mas nesse caso n vai funcionar, alguem tem q fazer o base CSS. Cria uma issue aqui no projeto pra criação do base.scss!

2023-08-08 00:33 UTC, Alecell commented
Adorei o PR! Vamos tentar seguir mais esse padrão no projeto!

2023-08-08 00:34 UTC, Alecell requested changes

2023-08-08 00:34 UTC, Alecell commented on src/components/preview/index.tsx
> +interface IPreview {
Esse preview component faz parte de outra task, não pode ir no mesmo PR!

2023-08-08 03:13 UTC, hxsggsz commented on src/styles/Swith.module.scss
> +    padding: 14px;
issue criado! Seria uma boa ideia trocar esse padding por um width e height fixo?

2023-08-08 03:50 UTC, hxsggsz commented on src/styles/Swith.module.scss
> +    left: 20px;
eu consegui adicionar o `right: 0` , mas para isso tive que adicionar junto o `left: auto` senão o switch ficava assim:
![image](https://github.com/Alecell/octopost/assets/103784814/fd4695db-9a08-4423-852f-93399c203d06)

e teve mais um problema fazendo essa refatoração, o transition não está mais funcionando com `transition: left 250ms ` , com `transition: right 250ms` e muito menos com `transition: all 250ms`. Na minha opinião a forma como estava tem mais ganhos, visto que é um componente que vai se manter igual em qualquer monitor ou celular. Então ele não vai precisar mudar para se adequar aos tamanhos de tela

o código antigo: 
``` 
&:checked[type="checkbox"]:before {
    left: 20px;
}
```

código refatorado:
 ```
  &:checked[type="checkbox"]:before {
      right: 0;
      left: auto;
    }
```

2023-08-09 03:01 UTC, Alecell commented on src/styles/Swith.module.scss
> +    padding: 14px;
Não, só `rem` mesmo e gg

2023-08-09 03:05 UTC, Alecell requested changes
Um pepino chato é que vc commitou o `base.scss` na mesma branch e não numa separada, isso é ruim, mas como era só colocar a branch sem mais nada acho que ta safe!

2023-08-09 03:05 UTC, Alecell commented on src/App.tsx
>  interface ITest {
Sua branch parece que ta antiga, precisa atualizar com a develop.

2023-08-09 22:31 UTC, aalmeida00 requested changes
Algumas modificações relacionados a styleguide e padrões que vamos adotar.

2023-08-09 22:31 UTC, aalmeida00 commented on .github/pull_request_template.md
> +Issue:
Acho que pode remover isso aqui, já foi pra master.

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/preview/index.tsx
> +}
Podemos extrair essa interface para um arquivo para interfaces desse componente?

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/preview/index.tsx
> +};
Mudanças de styleguide
componentes:

`function() Componente {}
`
Definimos os componentes como function para que fique diferente do que é uma função do componente, do que é um coponente.

Funçoes
`const func () => {}
`

E vamos evitar o destructuring de props.

```suggestion
function Preview(props): React.FC<IPreviewProps> {
  return <div>{props.previewText}</div>;
};
```

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/switch/Switch.tsx
> +}
Aqui os mesmos comentários do preview de styleguide

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/preview/index.tsx
Trocar o nome da pasta e do arquivo.

Preview (capitalize)
Preview.tsx

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/toggleSocialMedia/ToggleSocialMedia.tsx
> +}
Aqui o mesmo detalhe do preview

2023-08-09 22:31 UTC, aalmeida00 commented on src/components/toggleSocialMedia/ToggleSocialMedia.tsx
Mudar o nome do arquivo pra ToggleSocialMedia

2023-08-09 22:49 UTC, hxsggsz commented on src/components/preview/index.tsx
> +};
esse preview é de outro pr que ja foi aprovado, o certo seria eu abrir uma nova issue pra fazer essas modificações?

2023-08-10 00:51 UTC, Alecell requested changes

2023-08-10 00:51 UTC, Alecell commented on .github/pull_request_template.md
Ué, ta resolved, mas o arquivo ainda ta aqui

2023-08-10 00:51 UTC, Alecell commented on src/components/preview/index.tsx
Mais um marcado como resolved que não foi feito.

2023-08-10 00:51 UTC, Alecell commented on src/components/switch/Switch.tsx
Nome da pasta é `PascalCase` tambem

2023-08-10 00:51 UTC, Alecell commented on src/components/switch/Switch.types.ts
> +export interface ISwitch {
Anota isso no nosso styleguide, com excessão de componentes, todo o resto é export na declaração, salvo excessões!

2023-08-10 00:51 UTC, Alecell commented on src/components/switch/Swith.module.scss
> +    left: 50%;
Acho q dava pra melhorar, mas ta bom desse jeito!

2023-08-10 00:51 UTC, Alecell commented on src/components/toggleSocialMedia/ToggleSocialMedia.tsx
Mais um marcado como resolved que não foi resolved

2023-08-10 00:53 UTC, hxsggsz commented on src/components/toggleSocialMedia/ToggleSocialMedia.tsx
eu tinha apagado o arquivo mas todo push que eu faço esse arquivo é enviado pra pr junto com o componente de preview da outra pr por algum motivo

2023-08-10 01:48 UTC, closed without merging