Refactor preview
Alecell/octopost pull request #60
Opened 2023-08-11 16:51 UTC by hxsggsz

Issue: #59 

<details open> 
  <summary>
    <b>Refactor</b>
  </summary>

refactor the preview component to follow the styleguide and add tests
</details>

<details open> 
  <summary>
    <b>Changelog</b>
  </summary>

- change the folder name to CamelCase
- refactor the component to follow the styleguide
- add tests

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

2023-08-11 18:11 UTC, aalmeida00 requested changes

2023-08-11 18:11 UTC, aalmeida00 commented on src/components/Preview/Preview.tsx
> +  return <div>{props.previewText}</div>;
Precisa de uma div?
É um texto, o ideal nao ser uma tag mais semantica?

2023-08-12 01:07 UTC, aalmeida00 approved these changes

2023-08-13 16:08 UTC, Alecell requested changes

2023-08-13 16:08 UTC, Alecell commented on src/components/Preview/Preview.spec.tsx
> +    it('should render on screen the preview', () => {
não usar should, usar renders

2023-08-13 16:08 UTC, Alecell commented on src/components/Preview/Preview.tsx
> +  return <p>{props.previewText}</p>;
Sei que não tem grande importancia nesse momento, mas isso vai ser uma `div`, já deixa como `div` e não `p`

2023-08-13 21:15 UTC, aalmeida00 approved these changes

2023-08-14 22:25 UTC, aalmeida00 requested changes

2023-08-14 22:25 UTC, aalmeida00 commented on src/components/Preview/Preview.spec.tsx
> +      render(<Preview previewText="test" />);
Pensei melhor aqui revisando esse componente, ficaria melhor assim e ao invés de passarmos o texto via props, passamos via children, muito mais semantico ao mundo real.

```suggestion
      render(<Preview>test</Preview>);
```

2023-08-14 22:25 UTC, aalmeida00 commented on src/components/Preview/Preview.tsx
> +  return <div>{props.previewText}</div>;
E aí ao invés de usar props, usamos children. **acredito que talvez tenha que mudar a typagem do children que deixa de ser um string para ser um React Node
```suggestion
function Preview(children: IPreview) {
  return <div>{children}</div>;
```

2023-08-15 02:53 UTC, Alecell requested changes

2023-08-15 02:53 UTC, Alecell commented on src/components/Preview/Preview.tsx
> +  return <div>{props.previewText}</div>;
Assim acho que da pau man, c pa tem q ser assim
```suggestion
function Preview(props: IPreview) {
  return <div>{props.children}</div>;
```

2023-08-15 02:53 UTC, Alecell commented on src/components/Preview/Preview.types.ts
> +  previewText: string;
Ai no caso, precisaria que aqui fosse `children: React.Children`.

É legal dar uma olhada qual o melhor candidato a children nesse componente: https://github.com/typescript-cheatsheets/react#useful-react-prop-type-examples

2023-08-16 00:01 UTC, Alecell approved these changes

2023-08-16 00:09 UTC, Alecell commented
Precisa resolver os comentários do @aalmeida00 e atualizar a branch!

2023-08-16 00:32 UTC, aalmeida00 approved these changes

2023-08-16 03:03 UTC, merged