refactor: remove scope from commitizen
Alecell/octopost pull request #62
Opened 2023-08-11 18:16 UTC by flaviafreirec

Issue: #61 

<details open> 
  <summary>
    <b>Refactor</b>
  </summary>

- **Description**
Remove `scope` from commitizen 

- **Cause**
Remove `scope` from commitizen, because is not actively being utilized by team members.

- **Solution**
Remove `scope` from commitizen
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
Remove scope from commitizen
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

2023-08-11 18:19 UTC, aalmeida00 approved these changes

2023-08-13 16:07 UTC, Alecell requested changes

2023-08-13 16:07 UTC, Alecell commented on .czferc.js
> +    const scope = answers.scope ? `(${answers.scope})` : '';
Precisa ajustar a lógica de construção do commit pra não usar o scope também.

2023-08-15 02:49 UTC, Alecell approved these changes

2023-08-15 02:49 UTC, merged