feat: add landle and test button #63
Alecell/octopost pull request #65
Opened 2023-08-11 19:47 UTC by flaviafreirec

Issue: feat #63

<details open> 
  <summary>
    <b>Feature</b>

  </summary>

</details>

- **Description**
This Pull Request implement the UI Component Manager `landle` for develop and test components and add a test button to the `Testinho.tsx` file to facilitate testing and integration with Landle.

- **Cause**
Problems with component tests when they were done directly in the file `App.tsx`

- **Solution**
We'll use `landle` to enhance tests of the components of our project.
</details>

<details open> 
  <summary>
    <b>Changelog</b>

- add `landle` dependencies on `package.json`
- add a `test button` on `Testinho.tsx`
- add new file `Testinho.stories.tsx` for tests on `landle`
  </summary>

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

![testttt](https://github.com/Alecell/octopost/assets/54037222/e64c3a20-5680-4fe1-ad62-de9f6e3ebb81)

  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

2023-08-11 22:26 UTC, aalmeida00 requested changes

2023-08-11 22:26 UTC, aalmeida00 commented on src/components/Testinho/Testinho.stories.tsx
> +export const World: Story = () => <Testinho />;
Aqui precisa ser o nome do componente

```suggestion
export const Testinho: Story = () => <Testinho />;
```

2023-08-11 22:26 UTC, aalmeida00 commented on src/components/Testinho/Testinho.tsx
> +  const [newName, setNewName] = useState(name);
@Alecell 

Pedi pra ela escrever esse teste aqui no testinho porque vou usar ele pra deixar de exemplo pro Zunstand no pr #58

2023-08-13 16:05 UTC, Alecell requested changes

2023-08-13 16:05 UTC, Alecell commented on package.json
> +    "@ladle/react": "^2.17.2",
Esse tipo de dependencia precisa ir pro `devDependencies`, não é um `dependencie`

2023-08-15 02:47 UTC, Alecell approved these changes

2023-08-15 02:48 UTC, Alecell commented
@aalmeida00 só falta vc aprovar man!

2023-08-15 11:50 UTC, aalmeida00 approved these changes

2023-08-15 12:00 UTC, merged