Nico 35271444
Alecell/octopost pull request #7
Opened 2023-08-07 23:45 UTC by Luiginicoletti

Eu baguncei alguma coisa aqui mas esse é o commit do contador de characteres. Coloquei junto com o outro pra poder testar

2023-08-08 00:13 UTC, Alecell requested changes

2023-08-08 00:13 UTC, Alecell commented on src/pages/home/index.module.scss
> +body, h1, h2, h3, h4, h5, h6, p, blockquote, pre, dl, dd, ol, ul, figure, hr {
Normalizecss é uma lib

2023-08-08 00:13 UTC, Alecell commented on src/components/CharacterCountDown/index.tsx
Esse componente é só o countdown isolado, a tag apropriada pra ele não é o `p`, mas sim o `span`.

Ele deve receber o tamanho atual e o tamanho máximo.

O nome do componente é melhor que seja algo como "limit" ou derivador, countdown passa uma vibe de contagem regressiva, mas não é bem isso que ele é.

2023-08-08 00:13 UTC, Alecell commented on src/components/CharacterCountDown/index.module.scss
Se não tem estilos n precisa do arquivo

2023-08-08 00:14 UTC, Alecell commented
Nas proximas não precisa colocar print do código ou do file structure, mas colocar o print do componente na tela é MUITO bom, POG!!

2023-08-09 00:24 UTC, Luiginicoletti commented
Tudo corrigido!

2023-08-09 02:41 UTC, aalmeida00 requested changes
Verifica se esse PR é igual a esse aqui, https://github.com/Alecell/octopost/pull/25. Se for pode fechar esse.

2023-08-09 02:59 UTC, Alecell commented
@Luiginicoletti esse PR tem 3 versões ao longo dos seus PR's, da uma olhada no role, precisa ajustar!

2023-08-09 03:00 UTC, Alecell requested changes
Ta uns 3 níveis de código de outras branchs derivadas dessa branch

2023-08-09 20:53 UTC, closed without merging