Docs/readme
Alecell/octopost pull request #74
Opened 2023-08-12 03:26 UTC by GabrielTrindadeC

Issue: #72

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
Adicionado readme.md
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
![image](https://github.com/Alecell/octopost/assets/76929097/867555d4-6bcc-496f-9daa-a69492aaf9cb)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
</details>

2023-08-12 18:52 UTC, aalmeida00 requested changes

2023-08-12 18:52 UTC, aalmeida00 commented on README.md
> +Se tiver alguma dúvida ou precisar de ajuda, fique à vontade para entrar em contato com nossa equipe em nosso [Discord](http://discord.gg/fhutDfuDa9).
```suggestion
Se tiver alguma dúvida ou precisar de ajuda, fique à vontade para entrar em contato com nossa comunidade em nosso [Discord](http://discord.gg/fhutDfuDa9).

```

2023-08-12 18:52 UTC, aalmeida00 commented on README.md
> +Obrigado pelo seu interesse no OctoPost! Esperamos suas contribuições e esperamos que você aproveite o aplicativo tanto quanto nós gostamos de construí-lo.
Cabe falar sobre a licença de distribuição e tal.

2023-08-12 19:48 UTC, aalmeida00 approved these changes
🔥 💪

2023-08-13 15:51 UTC, Alecell approved these changes

2023-08-13 15:51 UTC, merged