Feat/#66
Alecell/octopost pull request #79
Opened 2023-08-14 15:53 UTC by Luiginicoletti

Issue: 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
  
In this pullrequest we did the first step of unifying the components into an **inputMaster** component.

There are other features that are being worked on by our teammates that as soon as they are ready they will be added here in this entry. We'll keep working on it.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
* Imported all **inputs** components into **inputMaster**
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
fullscren
![image](https://github.com/Alecell/octopost/assets/17785028/210dd7cb-c6f7-4479-a560-4e4be6c4af73)

TextArea
TextCopy
CharacterLimit
![image](https://github.com/Alecell/octopost/assets/17785028/5a5c18fb-c73f-4e99-bd10-8b2f4cf41226)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2023-08-14 21:13 UTC, aalmeida00 requested changes

2023-08-15 02:45 UTC, Alecell requested changes

2023-08-15 02:45 UTC, Alecell commented on package.json
> +    "typescript": "^5.1.6"
Essa branch ta atualizada com a develop?

2023-08-15 02:45 UTC, Alecell commented on src/components/InputMaster/InputMaster.tsx
> +const InputMaster = () => {
E se fosse `ComposeEditor`?

2023-08-15 02:45 UTC, Alecell commented on src/components/TextArea/TextArea.module.scss
> +  resize: none;
Deixa habilitado pra Y, é maneiro

2023-08-15 02:45 UTC, Alecell commented on src/components/TextArea/TextArea.spec.tsx
> +// import { render, fireEvent, screen } from '@testing-library/react';
Crime

2023-08-15 02:45 UTC, Alecell commented on src/components/TextArea/TextArea.tsx
> +    }
Esse componente não limita, ele é só uma referencia visual

2023-08-15 02:45 UTC, Alecell commented on src/components/TextCopy/TextCopy.tsx
Esse componente vai de vinagre

2023-08-17 18:06 UTC, Luiginicoletti commented
Resolved with new StyleLint

2023-08-17 21:22 UTC, Alecell approved these changes

2023-08-17 21:22 UTC, Alecell commented on src/components/ComposerEditor/ComposerEditor.tsx
> +import scss from '~components/ComposerEditor/ComposerEditor.module.scss';
nesse caso, como o scss ta no mesmo arquivo que seu componente, usar `./` ao inves de `~`

2023-08-17 21:22 UTC, Alecell commented on src/components/TextArea/TextArea.tsx
> +import scss from '~components/TextArea/TextArea.module.scss';
nesse caso, como o scss ta no mesmo arquivo que seu componente, usar ./ ao inves de ~

2023-08-17 21:22 UTC, Alecell commented on src/components/TextArea/TextArea.tsx
> +function CustomTextArea({ onTextChange }: ICustomTextAreaProps) {
Não desestruturar

2023-08-17 21:22 UTC, Alecell commented on src/components/TextArea/TextArea.tsx
> +    onTextChange && onTextChange(newValue);
Aqui sem a desestruturação, da pra fazer isso:

```suggestion
    props?.onTextChange(newValue);
```

2023-08-17 22:03 UTC, Luiginicoletti commented on src/components/ComposerEditor/ComposerEditor.tsx
> +import scss from '~components/ComposerEditor/ComposerEditor.module.scss';
Feito.

2023-08-17 22:04 UTC, Luiginicoletti commented on src/components/TextArea/TextArea.tsx
> +import scss from '~components/TextArea/TextArea.module.scss';
Pronto

2023-08-17 22:09 UTC, Luiginicoletti commented on src/components/TextArea/TextArea.tsx
> +function CustomTextArea({ onTextChange }: ICustomTextAreaProps) {
Pronto

2023-08-17 22:10 UTC, Luiginicoletti commented on src/components/TextArea/TextArea.tsx
> +    onTextChange && onTextChange(newValue);
Pronto.

2023-08-17 22:13 UTC, Luiginicoletti commented
Todas as sujestões foram atendidas.

2023-08-17 22:13 UTC, aalmeida00 requested changes

2023-08-17 22:13 UTC, aalmeida00 commented on README.md
> +## ![https://img.shields.io/badge/Electron-13.1-blueviolet](https://img.shields.io/badge/Electron-blueviolet)![https://img.shields.io/badge/TypeScript-blue](https://img.shields.io/badge/TypeScript-bl
Tá dando conflito nesse arquivo

2023-08-17 22:29 UTC, aalmeida00 approved these changes

2023-08-17 22:37 UTC, merged