Feat/#71
Alecell/octopost pull request #81
Opened 2023-08-14 19:55 UTC by leandrokzu

Issue: #71 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Added Normalize CSS
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

Normalize Css was imported into base.scss and old font-size style was removed from base.scss
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/61525671/e7e78729-ec54-4453-97f5-e42c4e43b29d)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [ ] Tests created
</details>

2023-08-14 21:28 UTC, aalmeida00 requested changes
Aponta o PR pra develop ao invés de master. Alecell:develop

2023-08-14 21:28 UTC, aalmeida00 commented on package.json
> +    "normalize.css": "^8.0.1",
Acredito que o normalize deve ser instalado como devDependency --dev

2023-08-14 21:34 UTC, aalmeida00 approved these changes

2023-08-15 02:05 UTC, Alecell requested changes

2023-08-15 02:05 UTC, Alecell commented on src/styles/base.scss
> -}
Vamos manter isso! Vai ter o import do normalize e as nossas customizações juntas!

2023-08-15 02:05 UTC, Alecell commented on package.json
> +    "normalize.css": "^8.0.1",
Isso aqui é um `dependency`, não `devDependency`

2023-08-17 12:46 UTC, Alecell approved these changes

2023-08-17 12:51 UTC, Alecell requested changes

2023-08-17 12:51 UTC, Alecell commented on package.json
> -    "zustand": "^4.4.1"
O build ta falhando. Por algum motivo o zustand foi removido das dependencias.

2023-08-17 17:05 UTC, leandrokzu commented on package.json
> -    "zustand": "^4.4.1"
vish, acho que pode ter sido no merge. Pra arrumar eu adiciono de novo, ou tem que arrumar usando o git?

2023-08-17 17:08 UTC, aalmeida00 commented on src/styles/base.scss
>  }
Rola colocar o html aqui?

2023-08-17 23:03 UTC, aalmeida00 approved these changes

2023-08-18 00:13 UTC, Alecell approved these changes

2023-08-18 00:13 UTC, merged